alpinejs/alpine

- index.html
- src/component.js
- src/utils.js
- test/bind.spec.js
- test/cloak.spec.js
https://vuejs.org/v2/api/#v-cloak
> Add x-cloak

- README.md
Add a lil bit of documentation for using x-bind with boolean attributes.
> Add x-bind usage for boolen attributes to README file

- README.md
added instructions to README for IE11 users
> added ie11 polyfill scripts to README

- README.md
There are now, if I count correctly, 9 directives available
> Fix directives count

- package.json
- rollup.config.js
Small Quality of Life improvement to show file size after successful build of the js file
> Add Filesize to build

- .github/workflows/run-tests.yml
This PR activates the test action on PR submission so the status will be reported before merging the PR.
It would fix #53.
> Enable CI on Pull Requests

- LICENSE.md
- README.md
> Add a copy of the MIT license

- README.md
A small ~~useless~~ PR to fix unclosed tags in readme.md
> Fix missing tags

- README.md
It's 4 properties now, not 3, sorry, only one single character change ;)
> Fix count of Magic Properties

- src/directives/bind.js
Fixes <option :selected="selected"></option> behavior
> Add "selected" attribute into boolean attrs list

- src/component.js
- src/index.js
- src/utils.js
Thanks for Alpine! Love using it!
I went through the source to finally understand how it works underneath and came across a few typos. Figured I could send in a PR for this.
Thanks again 👍🏼
> Fix a few typos

- dist/alpine-ie11.js
- dist/alpine.js
- src/directives/model.js
- test/model.spec.js
> Fix x-model .number modifier

- README.md
- dist/alpine-ie11.js
- dist/alpine.js
- src/component.js
- src/observable.js
This PR fixes reactivity in IE 11(due to functionality the current proxy polyfill doesn't support.)
> Fix broken reactivity in IE11

- test/bind.spec.js
Some tests for classes were not calling the assertions.
A linter would have probably caught this 😄
> fix(missing assertion calls in tests)

- README.md
Closes #152 
Issue resolution mentioned it might be a good thing to document and I tend to agree.
> Documentation: explicitly set x-data functions on window when using a bundler.

- src/utils.js
- test/utils.spec.js
Improvement based on [#187](https://github.com/alpinejs/alpine/issues/187).
Thanks, Flash!
> improve array unique values snippet

- dist/alpine-ie11.js
- dist/alpine.js
- src/component.js
- test/mutations.spec.js
Fixes #442 
~~I don't know how to write a good test for it.~~
UPDATE: Also, added a basic tests
> MutationObserver reset x-data when nested components are moved around

- src/component.js
- test/next-tick.spec.js
Minimal PR to address the nextTick issue when used with animations.
It also contains a test which fails with the current master branch.
> Defer nextTick to the next animation frame

- README.md
https://github.com/alpinejs/alpine/issues/573#issuecomment-644284789
> Make more clear how to use $dispatch with sibling nodes

- src/component.js
> Fix: default x-data to '{}' to in mutation observer initialiser

- test/bind.spec.js
The test descriptions for adding or removing multiple classes were flipped.
> test: fix flipped multiple classes test

- src/component.js
- src/utils.js
Benchmark: https://www.measurethat.net/Benchmarks/Show/8658/alpinejs-speed-up-transitionin-transitionout
> Boost checkings (filter > some)

- README.md
- README.pt.md
Full Portuguese translation of Alpine documentation for version 2.5.0.
> Portuguese translation for version 2.5.0 

- dist/alpine-ie11.js
- dist/alpine.js
- src/component.js
- test/watch.spec.js
Adds a special case for arrays so watcher will trigger every time their elements changes (support pop, push, shift, unshift, sort, etc)
> Feature - $watch with arrays

- README.es.md
- README.md
- Add documentation in README.es.md.
- Add a link to access it from the main README.
> Add documentation in Spanish

- README.de.md
- README.md
- Added full German translation of the main Alpine documentation for version 2.7.0
- Added reference to German translation in main documentation
> German translation for version 2.7.0

- README.de.md
- README.id.md
- README.md
I'm an Indonesian. I just added a translation for Bahasa Indonesia, hopefully it can help an Indonesian for reading the project's readme.
> added Indonesia translation

- README.md
- README.tr.md
- Added Turkish documentation in README.tr.md
- And link to it  in the main documentation (README.md)
> Turkish translation for the documentation

- README.zh-TW.md
> ![](https://user-images.githubusercontent.com/12410942/100896248-628f6d80-34f9-11eb-9305-2e5ce643bdbf.png)
> docs(zh-TW): fix missing code snippet

- README.ko.md
I would like to request a PR for the translated to korean version of the README.md in alpinejs
> Translation of Alpine.js's README.md to Korean

- README.ar.md
- README.md
Hi, i added Arabic Language (Readme.ar.md) and update main file.
> Arabic translation added & update main file

- README.ko.md
- README.md
And I also added the link README.ko.md to the original README.md.
> I would like to request a PR for the translated to korean version(completed a translation to korean) of the README.md in alpinejs

- README.ar.md
This PR adds RTL formatting for the Arabic readme file so it is easier for Arabic readers to read it directly on GitHub.
> Arabic readme: RTL formatting

- README.md
> 🔍 micro typo README.md

- README.md
- README.zh-CN.md
Thanks for @calebporzio and all contributors to create the amazing JS Framework.
I’m a Chinese native speaker and I have translated README to simplified Chinese(简体中文).
Hope to make Chinese Developer to learn Alpine.js easily~
> Add README translation of Simplified Chinese

- README.md
We've recently released 1.0 of Alpine.js devtools.
It's pretty stable and has the following features: 
- list components on a page
- inspect & edit component data 
- view eval errors (warnings tab)
> Add devtools link to README

- README.no.md
Adds a Norwegian translation of the documentation.
> Add Norwegian translation of the documentation

- README.zh-CN.md
> fix chinese typo

- README.fa.md
Adds a Farsi translation to the documentation, README.fa.md .
> Add Farsi translation of documentation

- packages/docs/src/en/magics/el.md
Use the same wording as in the demo
> Fix $el example in documenation

- packages/docs/src/en/directives/model.md
> Fix model docs

- packages/docs/src/en/advanced/csp.md
> Fix minor typos in csp.md

- packages/docs/src/en/essentials/installation.md
On the installation page
`3.0.5` => `3.0.6`
> Update hardcoded latest version in docs

- packages/alpinejs/src/directives/x-if.js
This is a change related to this bug: https://github.com/alpinejs/alpine/discussions/1535
I'm not sure if I fixed it correctly, but it solves the problem.
* **Alpine v2:** https://codepen.io/Niklan/pen/yLMZRoM
* **Alpine v3 before:** https://codepen.io/Niklan/pen/XWMOxKa
* **Alpine v3 after:** https://codepen.io/Niklan/pen/vYxbQZL
> Init directives for x-if contents after it's created.

- packages/docs/src/en/directives/html.md
Fixes a small grammar issue in `html.md`.
> chore: grammar in html.md

- index.html
- package-lock.json
Corrected playground page's missing parts to make it work out of the box.
> Fix playground sample page

- packages/alpinejs/src/utils/classes.js
x-transition in x-bind if you use functions don't works
https://github.com/alpinejs/alpine/discussions/1633
https://github.com/alpinejs/alpine/discussions/1458
> x-transition in x-bind if you use functions

- packages/alpinejs/src/directives/x-data.js
Fix related to: https://github.com/alpinejs/alpine/discussions/1664
> fix error where data was being hoisted to global scope introduced in 3.2.0

- packages/alpinejs/src/utils/styles.js
- tests/cypress/integration/directives/x-bind-style.spec.js
This fixes the issue mentioned here: https://github.com/alpinejs/alpine/discussions/1807
@KevinBatdorf Thanks for the initial bugfix. Could you please have a look?
> fix: set custom properties in style correctly

- packages/docs/src/en/upgrade-guide.md
Fixes link position (introduced in https://github.com/alpinejs/alpine/pull/1976). Sorry for that
> x-ref fix link

- packages/docs/src/en/plugins/persist.md
- packages/persist/src/index.js
- tests/cypress/integration/plugins/persist.spec.js
- tests/cypress/utils.js
This PR adds a to modifier to allow users to persist their data in an alternative storage.
> Persist to custom storage

- README.md
Added clarification on how to submit updates to the docs as per @calebporzio's demand.
https://twitter.com/calebporzio/status/1436028465434746880
> Added info on how to submit to docs.

- packages/trap/src/index.js
- tests/cypress/integration/plugins/trap.spec.js
This PR adds test for the x-trap bug fix affecting livewire entangle (#1986)
Co-Authored-By: @SimoTod
> added x-trap entangle test

- packages/alpinejs/src/directives/x-transition.js
- scripts/utils.js
Was checking the source code and found this 3 missing commas.
Hope that helps.
> Add missing commas

- package-lock.json
- packages/collapse/src/index.js
- tests/cypress/manual-transition-test.html
Fixes #2335 
Related discussion: #2334
Bug originally introduced in #2213
@Jumaniyozov please improve your mouse clicking record with this code ;-)
> Fix x-transition fast double click bug

- packages/docs/src/en/start-here.md
> The shorter for x-on

- packages/docs/src/en/directives/effect.md
Found this stray quotation mark on the `x-effect` docs page. Cheers guys, I'm enjoying the framework!
> Remove stray quotation mark

- packages/docs/src/en/plugins/morph.md
The button text is not visible so changing it's color to black.
> Change interactive visualization button text color (Morph plugin docs)

- packages/docs/src/en/directives/data.md
The ... didn't really make it clearer and did not add anything beneficial to the docs.
> Replace ... with closing tag character

- packages/alpinejs/src/utils/on.js
- tests/cypress/integration/directives/x-on.spec.js
Hello! This PR  fix trouble combining keyup event, key name and modificator "once". Issue: https://github.com/alpinejs/alpine/issues/2732
> Fix trouble combining keyup event, key name and modificator "once"

- packages/docs/src/en/directives/for.md
Ref: https://github.com/alpinejs/alpine/discussions/2830
Updates `x-for` documentation to state that keys must be unique.
> Update x-for documentation

- README.md
- descriptions where taken from the documentation
- also alphabetized list
- left out `portal` because I'm not sure what it is
> add description of new packages

- packages/alpinejs/src/directives.js
- packages/docs/src/en/advanced/extending.md
- tests/cypress/integration/custom-directives.spec.js
Failing test before the change: https://github.com/alpinejs/alpine/actions/runs/3594849581/jobs/6053624912#step:6:833
> Custom directive order

- .github/workflows/run-tests.yml
Bumps actions and also bumps node from 15 to 18
> run-tests: bump actions and node

- packages/mask/src/index.js
- tests/cypress/integration/plugins/mask.spec.js
Allow minus sign (-) at the start of the input to allow for negative values.
https://github.com/alpinejs/alpine/discussions/3324.
> x-mask $money allow for negative values

- packages/docs/src/en/directives/bind.md
- packages/docs/src/en/directives/data.md
- packages/docs/src/en/directives/on.md
- packages/docs/src/en/essentials/installation.md
- packages/docs/src/en/plugins/mask.md
Went through the docs as best as I could to clean up some 2-space indentations (and a 1-space indentation was found as well). There are more on the main page (https://alpinejs.dev/), but I couldn't find that page in source control.
> Cleanup more 2-space indents to 4-space

- scripts/build.js
Noticed a little bit of DRY code and addressed it.
> Reuse dot-json helper functions

- tests/cypress/integration/directives/x-bind-style.spec.js
e579cc8 introduced some changes to tests that appear to have been unnecessary and broke the tests.
> Fix tests broken by e579cc8.

- packages/navigate/src/page.js
Fixes https://github.com/livewire/livewire/discussions/6144
> [livewire] Update navigate page.js

- benchmarks/giant.html
- packages/ui/src/combobox.js
- packages/ui/src/listbox.js
Fix several typos, replace simplfy ->simplify, existence -->existence.
> Fix some typos

- packages/docs/src/en/plugins/sort.md
> Wrong plugin name in Sort docs
