alpinejs/alpine

package.json

Adds a version key to `package.json`. This will allows users to `npm i calebporzio/project-x` without requiring the package to be published to NPM.
Originally I started this branch hoping to swap `mix` for `rollup` to provide an optional ESM bundle in addition to the UMD. The ESM bundle cuts out a lot of boilerplate that UMD requires, lowering the file size quite a bit. Really useful for those that'll consume the package via npm. 
Getting the babel config working was a total nightmare though, and I eventually gave up. May take another crack at it later. Still wanted to contribute _something_, so here ya go.
---
Related #6

chore: add version to package.json

---

README.md
src/component.js
test/on.spec.js

This allows you to install an event listener on the window object and still have access to component state in the callback
This PR is unsolicited, feel free to close if it doesn't fit your vision.

Window modifier for x-on directive

---

src/component.js
test/bind.spec.js

Wanted to toggle the `hidden` [global boolean attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden), so I added it.
Was thinking that a boolean value should just toggle any attribute, but didn't want to jump that.

Add hidden to boolean attributes

---

README.md

This lets people preview the latest version's bundle's size.

Add a npm bundle size badge (minified + gzipped) to README

---

README.md

As the `Alpine` variable is not used in the installation example, eslint could throw a `'Alpine' is defined but never used` error which would cause a build to fail.
Simplifying the import statement and not setting a variable name fixes this issue.

Update the example import statement, fix eslint error

---

README.md

Updated the transition snippets to use the new Tailwind classes available in v1.2, so copy-pasters have an immediately working example.

Use Tailwind transition and transform classes

---

src/directives/if.js

Since there's no reasoning in the console warning (would be to verbose anyway), a small documentation link could be useful for curious developers.

Add documentation link to x-if warning

---

src/directives/for.js

I noticed that the warning would log out with `<tempate>` instead of `<template>`, so here's the fix 😄

Typo: `tempate` -> `template` in x-for warning text

---

README.md
dist/alpine-ie11.js
dist/alpine.js
src/component.js
test/watch.spec.js

You can now "watch" for data changes in an Alpine component using the new `$watch` magic method.
Example:
```html
<div x-data="{ open: false }" x-init="$watch('open', value => console.log(value))">
<button @click="open = ! open">Toggle Open</button>
</div>
```
(When the button is clicked, the new value of `open` is `console.log`'d)

Add $watch magic method

---

dist/alpine-ie11.js
dist/alpine.js
src/index.js

Allow third-party libs like Livewire to have better control over when Alpine initializes:
```html
window.deferLoadingAlpine = callback => {
// When some condition is met, call callback() and Alpine will load
}
```

Add window.deferLoadingAlpine()

---

dist/alpine-ie11.js
dist/alpine.js
src/component.js
src/utils.js
test/data.spec.js

Fixes #272
Inside utils.js the debounce function declares timeout variable for each call which preventing the timeout from being cleared and causes repeated component rendering.

Debounce timeout never gets cleared

---

src/component.js

Fixes #189.
Node(s) handled by the if-directive triggers mutation observer to reinitialize the handled node(s). 
In the case of ```x-if``` within ```x-for```, the node is reinitialized without additional value (provided by ```x-for```) resulting in eval reporting undefined object even though it shouldn't be

Fix mutation observer reinitializing element(s) in x-if within x-for usecase

---

README.md

Since the README is the only Documentation at the moment, I've found it easier to get a quick overview about the directives and magic props when I added a short description.
When you're not used to Vue those directives are not always obvious. 
[See changes in rich diff](https://github.com/alpinejs/alpine/pull/291/commits/61dd7c8c01d27a7f984a95e32a415b0d456e3cff?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8)

Documentation: added descriptions to directive & magic props overview in README

---

dist/alpine-ie11.js
dist/alpine.js
src/component.js

Remove pointless Walk through the $nextTick

---

dist/alpine-ie11.js
dist/alpine.js
examples/index.html
src/component.js
src/directives/for.js
test/for.spec.js

This is now possible:
```html
<div x-data="{ foos: [{bars: [{bobs: ['one', 'two']}, {bobs: ['three', 'four']}]}, {bars: [{bobs: ['five', 'six']}, {bobs: ['seven', 'eight']}]}] }">
<template x-for="foo in foos">
<div>
<template x-for="bar in foo.bars">
<div>
<template x-for="bob in bar.bobs">
<span x-text="bob"></span>
</template>
</div>
</template>
</div>
</template>
</div>
```
(This outputs:)

Fix nested x-for loop scoping

---

dist/alpine-ie11.js
dist/alpine.js
src/component.js
src/directives/if.js
test/constructor.spec.js
test/if.spec.js

In the following snippet, before this PR, "foo" was never getting set to "baz". Now it is.
```html
<div x-data="{ show: false, foo: 'bar' }">
<h1 x-on:click="show = ! show"></h1>
<template x-if="show">
<h2 @click="foo = 'baz'"></h2>
</template>
<span x-text="foo"></span>
</div>
```

Fix broken `x-if` element initialization

---

dist/alpine-ie11.js
dist/alpine.js
src/component.js
src/directives/if.js
test/if.spec.js

The following snippet was broken before:
```html
<div x-data="{ foos: [{bar: 'baz'}, {bar: 'bop'}]}">
<template x-for="foo in foos">
<div>
<template x-if="foo.bar === 'baz'">
<div>
<span x-text="foo.bar"></span>
</div>
</template>
</div>
</template>
</div>
```

Fix x-if inside x-for

---

dist/alpine-ie11.js
dist/alpine.js
src/component.js
src/directives/if.js
test/if.spec.js

Closes #348
When alpine runs the initial update calling initializeElements, it walks down the component children, resolving data and attaching elements.
When it finds a x-if, if the guard resolve to true, it attaches a new element after the template tag and calls another initializeElements on the new element. The second calls already binds data and attaches the required listeners. 
After that the first call continues and gets the next element which is now the one created by x-for but, since Alpine doesn't know, it duplicates any possible event listeners.
To fix it, similar to what we do for x-for, we should skip anything generated by x-if in initializeElements.
To allow the function to run correctly when called from the x-of handler, I've moved the key setter after the initializeElements …

Duplicate listeners when resolving x-if directives.

---

dist/alpine-ie11.js
dist/alpine.js
src/directives/bind.js
test/bind.spec.js

Closes #374. This fix isn't quite what was being suggested in the issue. The actual problem was that the order of operations (adding or removing the classes) was unknown, so the removal of a class might come after the addition of it and vice versa.
I've chosen to keep the footprint of the method the same near enough and instead sort the keys by the value before looping over them. This way, the classes that need to be removed (value evaluates to false) will become the iteratee first, and then new classes will be added afterwards.
If anyone thinks the method suggested in the PR is worth doing instead, let me know and I'll close this for someone else to implement or update the PR accordingly. Both have the same outcome either way and tests pass still.

Fix bound classes being removed unnecessarily

---

README.md

TODO: The japanese README should be updated as well.
closes: https://github.com/alpinejs/alpine/issues/342

explained that transition example uses tailwindcss classes

---

README.md

This was missing from the docs, just a simple addition. Not sure it closes any issues but is worth noting.

Updated README to include note about single root element

---

README.md

Personally, I find it very useful to be able to go to a package's repo and immediately see what the latest version is. I suspect others may be in the same boat.

Add npm version button to README

---

README.md

At Caleb's request... a PR to add the module/nomodule pattern to the docs:
https://philipwalton.com/articles/deploying-es2015-code-in-production-today/
https://caniuse.com/#feat=es6-module

Add module/nomodule pattern to the README

---

dist/alpine-ie11.js
dist/alpine.js
src/component.js
src/directives/html.js
src/directives/text.js

Not sure if `text.js` was intentionally left empty. I was thinking a filter idea so just want to move it to its own file for sake of readability. 
>update
updated this PR to include `html.js` file as well. It will be better for future updates and maintaince. Now every directive has its own file.

Refactor html/text directives into separate files

---

src/directives/bind.js

Thanks to @SimoTod  for his suggestion to apply the fix in the right file.   Fixes #366

Fixes #366 cursor position jumping to the end

---

dist/alpine-ie11.js
dist/alpine.js
package-lock.json
src/component.js
src/directives/bind.js
test/bind.spec.js

Closes #308 
Distinguishes between `x-bind:value` and `x-model` value bindings so radio value can be set from x-bind. Also forces `x-model` to be processed after `x-bind:value` for radios, so a radio input's value will be set before checking its value against any state values (allowing for a correct `checked` property).
p.s. Thank you for this awesome framework!

Implement value binding on radio inputs

---

dist/alpine-ie11.js
dist/alpine.js
src/directives/for.js
test/for.spec.js

Fixes #356
This has worked for me, but I don't know if it's the proper solution.
Includes tests.
Thanks

inherit extraVars in x-for scope

---

dist/alpine-ie11.js
dist/alpine.js
src/component.js
test/next-tick.spec.js

Fixes #333
When using x-for and updating the list, Alpine updates all the directives but ignores the x-for item and then it flushes the nextTick stack so the callbacks are currently running before x-for finishes its rendering. After that point, each element of the list calls either initializeElements or updateElements (each of them will try again to empty the nextTick stack).
~~To fix it, I've debounced the stack execution so it should run only at the end (either because the main refresh is the only call or it's the last call of a x-for loop).~~
~~I've duplicated the debounce function because it seemed it was conflicting but I might be wrong.~~
To fix it, will run the stack only if the root element of the update function is the Alpine component and we ignore element generated by x-for and …

nextTick runs before x-for finishes updating

---

dist/alpine-ie11.js
dist/alpine.js
src/directives/on.js
test/on.spec.js

Chrome and Safari (and, I suppose, all Chromium and Webkit browsers) have this behaviour where an Event (not a KeyboardEvent) with type "keydown" (and another with "keyup") is triggered on autocomplete input.
https://bugs.chromium.org/p/chromium/issues/detail?id=581537
This fix updates the `isKeyEvent` function by adding a check on the Event object type, and accepting only `KeyboardEvent`. This solves a problem of ghost key events that don't have a type property and cause an error when `keyToModifier` is called with `undefined` argument.
The first attempt to solve this was by fixing the `keyToModifier` function (https://github.com/zupolgec/alpine/commit/2a1f807d288ec2939ac7afdb636e128502efe669), but since the `isListeningForASpecificKeyThatHasntBeenPressed` function is doing nothing on …

Fixed detection of KeyboardEvents

---

README.md
dist/alpine-ie11.js
dist/alpine.js
src/directives/on.js
test/on.spec.js

This PR introduces a new `.self` modifier with the same behaviour as Vue's implementation. This should also make it easier to prevent event's bubbled from nested elements being handled by parent elements, as in the case of #378.
When used on an element, i.e. `<div @click.self="handle()">`, the `handle()` method will only be called (or expression evaluated) if the element triggering the event matches the element that registered it. This will remove the need to add several `.stop` modifiers to nested elements when you don't want any event bubbling for that particular parent / component.
I'm not sure if it's worth noting in the docs / README that chaining modifiers in different orders, for example `@click.self.prevent` and `@click.prevent.self`, won't have any effect on the order of …

Added new `.self` modifier for event listeners

---

dist/alpine-ie11.js
dist/alpine.js
rollup-ie11.config.js
rollup.config.js
src/index.js
test/version.spec.js

Closes #398 
- Add a "version" field on the `Alpine` global, populated by rollup from package.json
**Note for @calebporzio** to keep this number in sync you'll need to rebuild assets _after_ you've bumped the version _before_ publishing. So bump version -> rebuild -> commit -> publish

feat(alpine-version)

---

dist/alpine-ie11.js
dist/alpine.js
package-lock.json
src/directives/bind.js
test/bind.spec.js

Fixes #401 
This fix preserves any already-selected text range on the input value bound with x-model.
According to [the HTML spec](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#dom-textarea/input-selectionstart), only input elements whose text can be selected will return non-null selectionStart, selectionEnd, and selectionDirection values, so non-applicable input elements such as 'button' are skipped.
The test catches the `@select` event, fired on the element when its selection changes, to simulate an external change to the model's value.

Fixes #401. Preserve text selection on applicable inputs

---

dist/alpine-ie11.js
dist/alpine.js
src/directives/bind.js

Currently, `x-model` does not work on "hidden" inputs in Safari because of a recent bug fix (ironically to fix a different safari bug)

Fix safari bug for input type="hidden"

---

dist/alpine-ie11.js
dist/alpine.js
src/component.js
test/constructor.spec.js

Mutation Observer had a "return" instead of a "continue" in a for loop causing a bug when one of the mutations is not related to the others (in different parts of the DOM).
Mutation Observer would skip processing the rest of the mutations because of the `return`.
It was changed to `continue` and now every mutation gets processed and the bug is fixed.

Fix obscure mutation observer bug

---

dist/alpine-ie11.js
dist/alpine.js
src/directives/for.js
test/for.spec.js

Fixes #413 
When we update a x-for, if there is a new item we are wrongly calling update instead of insert. More details in the issue.

Fix x-on in x-for when updating

---

dist/alpine-ie11.js
dist/alpine.js
src/directives/bind.js
test/bind.spec.js

Fixes #436 
When the class list declaration in a x-bind:class is ended with a whitespace or contains multiple consecutive whitespaces an error is thrown.
This PR filters the class list after it is split and removes the empty classes.

Fix whitespace bug in x-bind:class class list

---

dist/alpine-ie11.js
dist/alpine.js
package-lock.json
src/directives/bind.js
test/bind.spec.js

Fixes #423
Updates #366 #367 #401 #404
I found that  Vue uses [an easy & better way](https://github.com/vuejs/vue/pull/3077/commits/13d01d078200fad765fcf09895b548377b7133a6).  it fixes the `cursor issue` by only **updating** the `el.value` if `old value` updated. (*Probably **value binding** happens multiple times, so `Safari` resets the `cursor positions` for each time*. )
My only concern if  `el.value`  check  would ever **throw an error** in other type of inputs. Would be nice if you guys can comment on this part.
I have tested this and it works. Not sure what type of tests would be suitable or do we need test at all for cursor positions? IMO we do not need **old cursor position tests**. But we can still consider to have simple test for all input types. (#407).  
I hope you guys can …

Using Vue way to fix cursor bug on Safari

---

README.md

People seems to use the 2.x.x CDN link in production so when we release a new version, if there are bug fixings changing the behaviour or accidental BCs, they'll get bugs straight into production without updating anything.
It should be obvious, but we should suggest they use a specific version number in production.

Minor improvement to readme file

---

dist/alpine-ie11.js
dist/alpine.js
examples/index.html
src/utils.js
test/transition.spec.js

Right now, Alpine only considers the transition-duration property.
Animation (and animation libraries such ad animate.css) usually define an animation-duration property instead. This means that Alpine runs all the stage steps in less then a millisecond and animations don't have time to complete.
This PR makes easier for developers to use css animations and css animation libraries without workarounds. Note, at the moment is already possible to set a transition-duration property matching the animation length but it's counterintuitive so this PR is more a nice to have.
Vue js for example support it without workarounds: https://vuejs.org/v2/guide/transitions.html#Custom-Transition-Classes
Original discussion: https://github.com/alpinejs/alpine/discussions/489
Mini demo: …

Feature - CSS animations

---

src/directives/bind.js

A small change, `.some` will stop iterating after the first match, but can still keep the "includes fuzzy"

replace .forEach with .some on x-bind checkbox

---

dist/alpine-ie11.js
dist/alpine.js
package-lock.json
src/utils.js

Closes #503.
This PR renames the `result` variable used inside of `saferEval` to `__alpine_result` to prevent conflicts with any `result` variables defined on the component data.
/cc @calebporzio @SimoTod @HugoDF

Rename `result` variable inside of eval utils

---

src/directives/for.js
test/bind.spec.js

2 issues:
1. missing `component` in call to internal transition function
2. invalid JS in the `object x-bind` test

new `x-bind` to object: fix transitions + tests

---

dist/alpine-ie11.js
dist/alpine.js
examples/index.html
src/component.js
src/directives/for.js
src/directives/if.js
src/directives/show.js
src/utils.js
test/bind.spec.js

Here are a few things I'd like input on:
1) Are there performance implications for running "saferEval" inside "getXAttrs". In other words, is Alpine slower now that there is an eval run every time it checks the attributes of an element. (Maybe caching is one potential answer - but there be dragons)
2) Currently this only works well when the bound directives object has non arrow-function attributes, because `this` binding is funky  with arrow functions. Would love to know if we can force the `this` of arrow functions reliably.
3) Do transitions still work with the getXAttrs -> .expression stuff?? (Because expression is no longer a string (for parsing classes and what not)

Add `x-bind`

---

README.md

Added an example of how to access $event and $dispatch inside of a
Javascript function.  This also includes adding an example of passing in
a Javascript name to x-on.

Update x-on, $event and $dispatch docs.

---

src/polyfills.js

fix #468 
IE actually has two deficiencies regarding `.contains()`: it doesn't support it for SVG elements and it also doesn't support it on `document`.
This PR only polyfills `SVGElement`, not the more generic `Node` (which would require a custom implementation instead of this one-liner), so `document.contains()` still doesn't work – but Alpine doesn't need that and users who rely on it can polyfill `Node.prototype.contains` themselves.  
So polyfilling `SVGElement` should suffice I think – opinions?

fix: polyfill SVGElement.prototype.contains for IE

---

README.md
src/component.js
test/constructor.spec.js
test/data.spec.js

This PR makes `$el` available within the `x-data` expression, for the reasons outlined in https://github.com/alpinejs/alpine/issues/471.
It also adds a notice about the availability of magic properties within `x-data` to the documentation.
close #471

Expose $el in x-data

---

src/directives/for.js
src/directives/if.js
src/utils.js

Closes #539 
rationalise the warnings for `template` elements:
- if a directive needs a template but isn't using one -> log warning
- if a directive expects a template but it has multiple root elements

feat(warn-template-multiple-root-elements)

---

dist/alpine-ie11.js
dist/alpine.js
examples/index.html
src/directives/show.js
src/utils.js
test/transition.spec.js

Fixes #533 (tested) |  #170 (tested, need more test) | #156 (partly tested, need more test) | `you tell me`
I have to refactor transition to achieve this solution. So there is a #542 Refactored Transition PR  of this PR which has same solution + refactored transitions to let transitions has its own space so it will be easier to work on it. (it was really hard to work on existing transition code). I have explained much more on #542 since they serve almost same purpose.  
This fix is quite self explanatory. I assigned few variables to check transitions and make sure and control how they are rendered.
By this, quick clicks overlapping transitions and wrong state of display issues will be fixed. There is also a test called `remaining transitions forced to complete if they exists` which tests …

Fix x show transition overlap

---

dist/alpine-ie11.js
dist/alpine.js
src/index.js

This commit adds a flag to pause/start the mutation observer.
This allows clients using Turbolinks and similar to do the needed DOM cleaning without data races.
This is a stripped down version of https://github.com/alpinejs/alpine/pull/455
Updates #319
Updates #372

Allow clients to pause the observer

---

src/directives/bind.js

Some dom elments change their internal state when an attribute is modified.
Namely the `audio` element stops playing if you modify it's `src` attribute even if it's value does not change. Therefor in the following example
```html
<div x-data="{ src: '...', i: 0 }>
<audio x-bind:src:"src" controls></audio>
<button x-on:click="i++">clicking this should not effect the audio</button>
</div>
```
the audio will stop playing every time the button is clicked.
This PR removes this unexpected behavior by only setting an attribute if it's value is changing.

Don't modify attribute if set to the current value

---

src/component.js
src/directives/bind.js
src/utils.js

We're taking "class names" and converting them to a list of classes in a couple of spots, this extracts that functionality to a util so we don't forget to filter out `''` for example.
Shouldn't affect existing functionality.

Extract convertClassStringToArray util

---

src/directives/model.js
test/model.spec.js

Closes #296 
**Changes**
- Extract `safeParseNumber` from existing `number` modifier code (for `select` and other non-checkbox inputs) - doing this means bundle size is the same/smaller despite adding new functionality
- Apply `safeParseNumber` during checkbox `x-model` computation
**Use case**
Use case is as follows (per the Issue), I've copied it verbatim into a new test.
> The example below shows the problem - the second checkbox is checked by default and can not be unchecked by clicking it.
```html
<div
x-data="{
selected: [2]
}"
>
<input type="checkbox" value="1" x-model="selected" />
<input type="checkbox" value="2" x-model="selected" />
<input type="checkbox" value="3" x-model="selected" />
<input type="checkbox" value="4" x-model="selected" />
</div>
```

Feature: x-model checkbox array `.number` modifier

---

package-lock.json
package.json

The current build is failing. It seems there's some incompatibilities between the version of babel/preset-env we use and the latest version of node. This happened to other libraries as well (For example Laravel mix, see https://github.com/JeffreyWay/laravel-mix/issues/2383). 🤷 
Updating babel/preset-env to the most recent version fixes the build process.
I've also run 'npm audit fix' since there were a lot of low lever security warnings
`found 1523 low severity vulnerabilities in 961 scanned packages`
All fixed without any BCs.

Update babel/preset-env and fix audit warnings

---

README.md

Not sure if this was supposed to have some other code content, or was just mistakenly copied?

Remove x-cloak code block from x-spread docs

---

README.md

Fixes #602 
The x-spread example code had a typo with x-data where it was missing '()' at the end of the function name.

Fix x-spread example

---

dist/alpine-ie11.js
dist/alpine.js
src/utils.js
test/spread.spec.js

This pull request ensures that the `$event` special variable is passed to event handlers defined as functions when using x-spread, as an alternative to having to reference another function by name in the event handler definition.
Closes #627 - more context in that issue.

Ensure event object is passed to handlers defined as functions using x-spread

---

test/model.spec.js

I left out writing test for these input types `<input type=["file", "image" | "submit" | "button"]>` because I believe these input types don't require two-way data binding for any use case scenario and `(type=" file | image ")` were also not specifically implemented. 
Closes #407

Tests x-model binding for all input types

---

dist/alpine-ie11.js
dist/alpine.js
src/utils.js
test/model.spec.js
test/show.spec.js

`x-show` will always be processed after bindings.
`x-model` will always be processed before event listeners.
No matter what order directives are in.
Closes #434

Sort directives for better predictability

---

package-lock.json
src/component.js

Some changes that were part of https://github.com/alpinejs/alpine/pull/315/files aren't needed any more.
The relevant use-case's tests still pass without the guard since it's a specific instance of "bind should be evaluated before model"

remove unecessary directive ordering clause

---

README.md

This closes #637.
PS: It might be useful to test the polyfill on IE11 and Safari. I don't need to support IE11 or Safari in my current project, but the polyfill included works fine in both Firefox and Chromium.

Document how to use `template` in `svg` elements using a polyfill

---

src/utils.js
test/bind.spec.js
test/utils.spec.js

Just added numbers to the attribute parsing regex so that it doesn't silently remove them.
Motivating example is SVG line elements that take `x1`, `y1`, `x2`, `y2` attributes. Alpine has been trimming those down to `x` and `y`.
Closes #666

fixes numeric attributes and adds test

---

README.md

I noticed that the `x-model.number` modifier is not mentioned anywhere, this adds a short example for it.

docs(x-model `.number` modifier)

---

src/utils.js

This warning message is a bit misleading, the template[x-if] tag requires a single child element, not a single child node (because text nodes are also nodes)
- It can have some empty text nodes around the single child element
- It's not good if it has a single text node as a child.

Correct wording of warning message

---

README.md
dist/alpine-ie11.js
dist/alpine.js
examples/index.html
src/directives/for.js
test/for.spec.js

This PR adds support for the `x-for="i in 10"` syntax that can be found in Vue. Lots of people have come to us with questions lately about how to replicate this in userland, but honestly the syntax is quite verbose and ugly.
The equivalent of `i in 10` would be `i in [...Array(10).keys()]` which, in my opinion, isn't too nice to look at and a bit of a pain. 
The only thing to note is how it compares to Vue, **Vue will start the count at 1**. So, the first value of `i` in `i in 10` would be `1`. 
~~With this implementation in Alpine, **the first value of `i` will be `0`**, since the `Array` itself starts at `0`. Happy to change this though and make it more in line with Vue's implementation if it means that the PR will get merged, I can imagine a lot of people being happy with this syntax …

feature(x for over range)

---

src/directives/text.js
test/constructor.spec.js
test/custom-magic-properties.spec.js
test/data.spec.js
test/debounce.spec.js
test/dispatch.spec.js
test/for.spec.js
test/if.spec.js
test/lifecycle.spec.js
test/model.spec.js
test/mutations.spec.js
test/nesting.spec.js
test/next-tick.spec.js
test/on.spec.js
test/readonly.spec.js
test/ref.spec.js
test/spread.spec.js
test/strict-mode.spec.js
test/text.spec.js
test/watch.spec.js

The `x-text` directive sets `innerText` on the element. The problem is that `innerText` is [only available on elements based on `HTMLElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText) but not `SVGElement` which is the base for e.g. the `<text>` SVG element. 
~~So instead of blindly setting `el.innerText` we now first check if it's actually an HTML element and otherwise fall back to setting `el.textContent` which is [part of the `Node` interface](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent) that all elements are based on.~~
Based on the discussion in #734, this PR swaps `innerText` out for `textContent` because they behave identically (at least when setting the value) and the latter is [part of the `Node` …

Make x-text work on SVG elements

---

README.md

This pull request adds a section to the `README`, to document the `collection` paramater in `x-for`, with an example.

Add collection param to x-for docs

---

dist/alpine-ie11.js
dist/alpine.js
src/component.js
test/watch.spec.js

This pull request replaces the `self.getUnobservedData()` method used inside of the watcher logic with the `self.unobservedData` property on the component.
The reason for this change is that when the membrane was being unwrapped, any magic properties on the `$data` object would be removed, meaning magic properties could not be watched for changes.
An example of this might be with Spruce, where somebody would want to watch for changes on the `$store.example.data` property, but because the `comparisonData` object did not have a `$store` key, it would simply fail. This opens up a lot of opportunity for cooler magic properties too (despite the fact that it's not a documented API) and also means that these libraries don't need to implement their own watcher logic.
This also isn't a huge change …

feature(allow watching for changes on magic properties)

---

src/component.js

`$wire` and other custom magic properties are currently broken in IE11.
IE11 uses a proxy polyfil that "seal" the object, meaning that no properties can be defined/redefined after the proxy is created so they need to be set earlier.

Add magic properties support in IE11

---

dist/alpine-ie11.js
dist/alpine.js
examples/index.html
src/directives/bind.js
test/bind.spec.js

This PR fixes an issue where non-string values couldn't be bound to a checkbox's value. An example would be trying to bind an integer / number:
<input type="checkbox" x-data :value="100">
The value of the checkbox would actually be "on" due to the typeof value === 'string' check inside of the checkbox handler. This PR replaces that check with a value truth check and makes sure that it's not a boolean, then casts the value to a string using String(value).
This could be done in user-land using x-bind:value="String(100)" or template literals x-bind:value="${value}" but I'd say that it's a bit of a bug with the framework.

 fix(allow binding non string values to checkboxes)

---

README.md

Adding a note to the docs for `x-bind` to make it clear to chain `.toString()` to the value if you need to persist a false value on a bound attribute.

Docs: Add note to chain .toString() to persist  false

---

README.es.md
README.md

A couple of people in the Discord came in wondering why code where `x-init` was defined inside an `x-spread` object wasn't working as intended.
Clarify this in the README.
Unfortunately my Japanese, Russian, Portuguese and Chinese chops aren't up to scratch 😄 so only updated in Spanish/English.

Docs: point out that x-init and x-data can't be "spread"

---

src/directives/bind.js
src/directives/model.js
src/utils.js
test/model.spec.js

Closes #814 
Some `el.checked` are being generated with loose equality (`==`), but in the x-model checkbox array case, unchecking was impossible due to a strict equality check (`!==`) in the "uncheck value" branch.
Extract the `el.checked` code to a util & use it where relevant (should help us keep it more consistent).

Improve consistency of `checked` attribute value comparisons

---

dist/alpine.js
src/utils.js
test/spread.spec.js

`x-spread` does not fully support `x-transition:leave`, `x-transition:transition:leave-start` and `x-transition:transition:leave-end`.
Currently `ensureStringExpression` is only applied to `x-transition:enter`, `x-transition:enter-start` and `x-transition:enter-end`.
Fixes #795

Transition leave support in x spread

---

dist/alpine-ie11.js
dist/alpine.js
src/utils.js
test/for.spec.js

Closes #839. The problem was being caused by the `isNumeric` utility using `isNaN()` on arrays. 
When an array only contains 1 item, that is numeric, it will converted to a `Number` object that holds that value of the first item, therefore passing the `isNumeric` check. This PR just changes it to check that the `subject` being passed through is **not** an array using `Array.isArray`.

fix(x-for): issue with range iteration and numeric arrays

---

dist/alpine-ie11.js
dist/alpine.js
src/component.js
src/directives/for.js
src/directives/if.js
src/directives/show.js
src/utils.js
test/transition.spec.js

Before this PR, given the following code:
```
<div x-data="{show: true}">
<button @click="show = ! show">Toggle</button>
<div x-show="show">
<div x-show.transition="show">
// Contents
</div>
</div>
</div>
```
If you press the "toggle" button, then press it AGAIN while the "out" transition is still playing, instead of transitioning back in mid-way, the contents would immediately disappear.
This only happens when an x-transition is wrapped by an x-show without a transition.
This PR fixes this case, but rejecting the entire show directive stack at the component level once any transition within it has been cancelled.

Fix overlapping transitions with parent x-shows

---

dist/alpine-ie11.js
dist/alpine.js
src/directives/bind.js
test/bind.spec.js

When passing an `undefined`/`null` result to a `:class` binding, it would die calling `split` in `convertClassStringToArray`. 
Fixes #825

Fix "Cannot read property 'split' of undefined" error on empty class binding

---

README.id.md

Replace `sihir` to `ajaib`. The word `ajaib` is more used than `sihir`.

fix: translation

---

src/component.js

Opening this PR to make it easier to understand my intent of #835 
The `canonicalComponentElementReference` may be needed to compute the initial state but it doesn't seem needed after that. More importantly, magic helpers in some cases need access to the most current cloned component, not the canonical component (which is about to be deleted).
Relevant part of the code:
https://github.com/alpinejs/alpine/blob/master/src/component.js#L25

Helpers to receive access to cloned component

---

README.md

A lot of people are asking which events they can use (not aware that the types of events are not Alpine.js-specific).
This should clear that up by linking to MDN "Event Reference"

docs: add link to MDN "Event" on `x-on`

---

README.ja.md

Japanese Readme was missing the $watch and the security and V3 roadmap sections, so I added them.
Please let me know if you have any suggestions.

Update japanese Readme translation

---

examples/index.html
src/component.js
src/utils.js
test/error.spec.js

Closes #783 
from these discussion points on the other PR:
- https://github.com/alpinejs/alpine/pull/862#issuecomment-732275009 
- https://github.com/alpinejs/alpine/pull/862#issuecomment-732293276
Implement the suggestion from the latter comment.
Errors are logged as follows:

Feat: better (eval) error messages/context

---

README.md
dist/alpine.js
src/directives/bind.js
src/directives/for.js
src/directives/text.js
test/spread.spec.js

This breaks because expressions are functions in x-spread, and when the output is defined, it attempts to run a String operation on it.
```js
if (output === undefined && expression.match(/\./)) {
output = ''
}
```
...which causes an error. This fix will just cast the function there to a string so it won't error out.
Fixes #957

Cast x-spread expression to string

---

src/utils.js

The error can then be read using:
```js
// might need to listen to "error" as well for non-async eval errors
window.addEventListener('unhandledrejection', (event) => {
console.log(event.reason.el, event.reason.expression, event.reason.toString())
})
```

Attach el + expression to eval error

---

dist/alpine-ie11.js
dist/alpine.js
src/directives/on.js

This PR is in response to #1053. It definitely seems like something that should be supported, so here you go.
The test suite wasn't playing very nice with me, I couldn't get the `.debounce` tests to work with the `.away` modifier, even though it's all working correctly in the browser.
I'll give it another go later on, but for now, here is the relevant logic.

feature: add support for debouncing x-on.away

---

README.md

This resolves #830. I think it's a valid point, anybody who wants to copy and paste this example into a fiddle to see how each thing works would be given an error / warning about multiple root nodes.

fix: misleading example in docs

---

src/directives/for.js
test/for.spec.js

Not sure if there's a specific reason why `x-for="i in n"` isn't allowed with n = 0. Allowing it to be 0 doesn't break anything, corresponds with the documentation (0 = integer), and makes if more convient to dynamically create/remove DOM elements where at some point n can become 0 and all DOM elements should get removed.
Simple example case:
```javascript
<div x-data="
{
maxSeats: 3,
seats: [],
availableSeats() {
return this.maxSeats - this.seats.length;
},
takeSeat(seatNumber) {
this.seats.push(seatNumber);
}
}"
>
<template x-for="seat in seats">
<button type="button" style="width: 70px; height: 50px; border: 2px solid red; margin: 1rem;">TAKEN</button>
</template>
<template x-for="i in availableSeats()">
<button type="button" @click="takeSeat(i)" style="width: 70px; height: 50px; …
```

Allow integer n to be 0 in for-loop

---

README.md

Closes #1091. Think this is a fair change since `x-cloak` should always have precedence over other CSS `display` properties.

fix: x-cloak css in README

---

dist/alpine-ie11.js
dist/alpine.js
src/component.js

This fixes an issue where if you have a Livewire component which has an Alpine component in it, that has nested Livewire components that also have Alpine in them. Adding a new nested Livewire component dynamically triggers an Alpine error
> Uncaught (in promise) TypeError: Cannot read property '$wire' of undefined
See this Livewire PR livewire/livewire#2517, which is a failing test, and issues linked in that PR for more details.
What is happening, is Livewire calls clone on Alpine's elements in `alpinifyElementsForMorphdom()` here
[livewire/livewire/js/component/SupportAlpine.js#L129](https://github.com/livewire/livewire/blob/b647ac63378ea02bdac975f70a4e57aea84bda0b/js/component/SupportAlpine.js#L129)
But this method is called in the `onBeforeElUpdated` morphdom hook here …

Fix nested alpine with nested livewire

---

examples/index.html
examples/tags.html

Due to the missing charset meta tag, the browser (Firefox in my case) throws this error:
`The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.`
[Here's an explanation](https://www.w3.org/International/questions/qa-html-encoding-declarations) from W3C regarding declaring the `charset` meta tag.

Add charset meta tag to the examples

---

src/component.js
test/lifecycle.spec.js

This makes it possible to add x-init logic to all elements programmatically.
No behavior is broken or changed, we just read the attribute after running the "before initialized" callbacks.
Also makes sense for "on before initialized" to be able to affect how the initialization process works.

Fetch x-init after running onBeforeComponentInitialized

---

dist/alpine-ie11.js
dist/alpine.js
src/component.js
src/directives/on.js
test/on.spec.js

Fixes: #1171
I'm not familiar enough with the project to know what I need to do to test this or if it's the right approach, but it does appear to resolve the problem for my simple example.

Remove stale event handlers when nodes are readded to the document.

---

README.md

Adds a link to the Norwegian translation of the documentation, in the English readme file.
Related to #1211 
The use of lowercase in the name of the language in the string is intentional, as language names in Norwegian are always typed in all lowercase.

Add link to Norwegian translation in English readme

---

dist/alpine-ie11.js
dist/alpine.js
src/directives/bind.js
test/model.spec.js

Fixes #1266
As per specs (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select)
`Each <option> element should have a value attribute containing the data value to submit to the server when that option is selected. If no value attribute is included, the value defaults to the text contained inside the element.`
This means that options already return text when value is not defined so we don't need that `||`.
Note that `||` breaks any cases where the option value is an empty string since it resolves to false so the code incorrectly uses the option text. 
This issue wasn't noticed earlier because the empty value is usually the first option so the browser just displays it.
Bug: https://codepen.io/SimoTod/pen/rNjqXQx
Fix: https://codepen.io/SimoTod/pen/xxgyvQg

Fix x-model not selecting falsy values in select dropdown

---

packages/docs/src/en/advanced/extending.md

Little PR to remove the `el` arg in the `evaluate` docs as the element is already bound as the first arg in this instance of the evaluate method.

Removes unnecessary el argument in evaluate docs

---

packages/docs/src/en/essentials/lifecycle.md

`watch` is not an directive, it is an magic method

Change x-watch to $watch in documenation

---

packages/docs/src/en/advanced/extending.md
packages/docs/src/en/advanced/reactivity.md
packages/docs/src/en/alpine-101.md
packages/docs/src/en/directives/effect.md
packages/docs/src/en/directives/for.md

Found a few typos in the docs, I listed them [on the Issues page](https://github.com/alpinejs/alpine-next/issues/15) before being referred to their location.
I fixed all instances of any of the named typos found.

Fix typos in the docs

---

packages/alpinejs/src/utils/classes.js
tests/cypress/integration/directives/x-bind:class.spec.js

A discussion about this issue can be found here: https://github.com/alpinejs/alpine/discussions/1525
Description:
Remove classes under false condition before adding classes under true condition to prevent classes from a true condition being removed if a false condition has the same class.
Changes:
- Made a suggested change from @KevinBatdorf
- added unit test

Fix x-bind:class directive using object syntax removes classes that are in a true condition when the class is also present in a false condition

---

packages/alpinejs/src/directives/x-bind.js
tests/cypress/integration/directives/x-bind.spec.js

This pull request fixes an issue where non-existent / undefined nested properties in an object would bind the literal string `"undefined"` instead of an empty string, which was the old behaviour in 2.x.
This behaviour was already implemented as part of the `x-model` binding logic, but was missing from direct `x-bind:` expressions.

fix: binding undefined nested value

---

packages/alpinejs/src/directives/x-for.js
tests/cypress/integration/directives/x-for.spec.js

A discussion about this issue can be found here: https://github.com/alpinejs/alpine/discussions/1520
Description:
Fix an issue with x-for where parsing the item name out of parenthesis would cause an error if spaces where present around the item name and index was not used.
Example:
-> This fails:
```<template x-for="( item ) in items">```
-> This succeeds:
```<template x-for="(item) in items">```
Changes:
- Fixed an issue with trimming whitespace around the item name in x-for
- Added unit test

x-for referenceError undefined when spaces are present in parenthesis

---

packages/docs/src/en/essentials/installation.md

I have been trying to upgrade my existing Alpine 2.X installation to Alpine 3.X for some time but always had some errors. 
I finally stumbled upon the solution to my problem today in the documentation under "[Extending](https://alpinejs.dev/advanced/extending#via-npm)":
Apparently the reusable data code needs to be executed BETWEEN the import of `Alpine` and `Alpine.start()`.
I hope that hint might be helpfull for others, too.

Documentation: Added hint in installation.md

---

packages/alpinejs/src/alpine.js

This would fix #567 or be one way to approach it. Example:
```html
<div x-data="{ready: false}" x-process="ready">
<span x-ignore>
Not processed until `x-process` is truthy
</span>
</div>
```
We can use `initTree` in a plugin like this:
```js
Alpine.directive('process', (el, { expression }, { Alpine: { initTree }, evaluateLater, effect }) => {
const evaluate = evaluateLater(expression)
effect(() => {
const ignored = el.querySelectorAll('[x-ignore]')
evaluate(result => result && ignored.forEach(n => {
n.removeAttribute('x-ignore')
n._x_ignore = false
initTree(n)
})
)
})
})
```
I set up a demo here: https://codepen.io/KevinBatdorf/pen/KKmPqML?editors=1010

Expose the initTree method

---

packages/alpinejs/src/magics/$watch.js
tests/cypress/integration/magics/$watch.spec.js

Also noticed it on the [webpage](https://alpinejs.dev), but that doesn't seem to be open source so can't PR there:

Fix "dependancies" typo

---

packages/docs/src/en/directives/on.md

The modifier is `.escape`, not `.esc`

Fix x-on .escape modifier documentation

---

packages/alpinejs/src/lifecycle.js
tests/cypress/integration/directives/x-data.spec.js

- `closestRoot` uses `el.matches` which requires a DOM Element
- `outNestedComponents` was using `parentNode` that doesn't always return a DOM Element (e.g. html.parentNode. returns document which is a Dom Node). `parentElement` instead will return null if the parent node is. not a DOM Element.
- ⚠️ I had to change `closestRoot(el.parentNode || closestRoot(el))` to `closestRoot(el.parentNode)` but I'm not sure about your original intentions so it might not be suitable. Reason: `closestRoot(el)` always returns the current element if `el` has an `x-data` attribute, so does `closestRoot(closestRoot(el))`. This means that `outNestedComponents` would filter out all the components when `x-data` is on the html tag. All test pass but I thought it was important to highlight this point since there …

Bug - Add support for x-data on html tag

---

packages/intersect/src/index.js

A few more like this and the plugin will be *negative* 311 bytes. 😝

Remove leading blank line in intersect plugin

---

packages/persist/src/index.js
tests/cypress/integration/plugins/persist.spec.js

This PR fixes an anomaly which we can see on the documentation page: https://alpinejs.dev/plugins/persist.
When there are 2 components on the same page using the same property, the last one is setting the value in local storage as expected but when reloading the page, only the first component is initialised correctly whilst the second component uses the default of the first one. I appreciate this is not a real use case, the 2 components won't communicate with each other out of the box after the page is loaded so they would behave weirdly but I think they should be consistent.
To replicate
- go to https://alpinejs.dev/plugins/persist#how-it-works
- scroll down to the example (note that above there is another example using the same component)
- increment the counter
- reload the page
- note …

Bug ($persist) Multiple components

---

packages/alpinejs/src/directives/x-data.js
tests/cypress/integration/custom-data.spec.js

Bug description: The init function that gets called automatically doesn't have access to the parent scope while x-init does.
Mentioned in #1674 and #1711
Relevant changes:
- changed simple function call to `evaluate` so the function gets full access to all Alpine magic.
- removed .only from 2 tests in custom-data.spec.js since the other tests were not running
- added test for the specific use case which fails without the fix (See https://github.com/alpinejs/alpine/runs/3189986654?check_suite_focus=true#step:6:72)
- added minimal test for `destroy` as that line of code was updated as well
Note:
I didn't run many tests for `destroy` since we might need a follow-up. In the current implementation, we call `undo` first and then `destroy` which means that the scope is removed before we call …

Bug: init() function doesn't have access to the parent scope

---

packages/alpinejs/src/utils/on.js
packages/alpinejs/src/utils/styles.js
tests/cypress/integration/directives/x-bind-style.spec.js

Changes in on.js are just coding style tweaks.
The bug is fixed styles.js 
When using an object, css properties can be defined using the camelCase names (when using the dot syntax is actually mandatory e.g. `style.myProperty`) but when we set them using `setProperty`, they need to use the real css name which is always dash-separated.
Instead of changing the transition file, I decided to just convert the property to kebab case in setStylesFromObject to make it future proof since people could face the same problem when binding styles.
No automated tests for the transition bug because the property changes too fast and I couldn't capture the change with cypress. Manually tested on chrome, firefox, safari and edge (Mac OS).
I've added additional tests for x-bind:style 
Mentioned in #1914 and …

Fix regression in x-transition

---

packages/docs/src/en/directives/if.md

I was doing some testing and noticed that `x-show` sets the inline style: `style="display: none;"`

Fix in docs about x-if directive

---

packages/alpinejs/src/directives.js
packages/docs/src/en/plugins/intersect.md
packages/intersect/src/index.js
tests/cypress/integration/plugins/intersect.spec.js

This PR
- Adds `:enter` `:leave` value directives to `x-intersect`.
- No breaking changes. `x-intersecet="[expression]"` still works as expected. 
- Improves existing `x-intersect` tests. (old ones had issues)
- It was very cheap to achieve such a high demanding behavior. 
| Directive      | Description |
| ---            | --- |
| `:enter`       | Applied only entering phase. |
| `:leave`       | Applied only leaving phase. |
```html
<div x-intersect:enter="shown = true">...</div>
```
```html
<div x-intersect:leave="shown = false">...</div>
```
```html
<div  x-intersect:enter="shown = true" x-intersect:leave="shown = false">...</div>
```

feature: Value/Modifier based intersect

---

packages/docs/src/en/plugins/persist.md

Feel free to reword it to make it clearer.
A few people are trying to use `$persist` with `Alpine.data` but all examples on the docs use arrow functions.
Alpine tries to bind the custom context [here](https://github.com/alpinejs/alpine/blob/main/packages/alpinejs/src/datas.js#L13) but in javascript is not possible to re-bind `this` for arrow functions.
This applies every time we try to use `this` to define a property value in Alpine.data but currently `$persist` is the only magic that needs it. Using `this` inside a function defined in x-data works as expected since at that point the object has been "Alpinefied" by the custom evaluate function.

Add instructions to use $persist with Alpine.data

---

index.html
packages/alpinejs/src/directives/x-model.js

This PR 
- fixes #1909
- fixes #1862
- fixes #1810
- fixes #1501
Fix was very simple as Safari triggers `autofill` event as CustomEvent instead of `input` event, even Alpine handles customEvent but it did not handle the assigned value properly. So i just fixed that part.
I don't have an iOS device to check but so far i could only check desktop safari and its seems fixed. It would be nice to have some feedbacks if anyone can try this.

fixed safari autofill bug

---

packages/trap/src/index.js
tests/cypress/integration/plugins/trap.spec.js

This PR fixes
- #1959
- #1962
- Improves tests
This would break in current `x-trap`
```html
<div x-data="{ open: false }">
<button @click="open = true">Open Dialogue</button>
<div>
<div x-trap="open" x-show="open">
<input type="text" placeholder="Some input...">
<input type="text" placeholder="Some other input...">
<button @click="open = false">Close Dialogue</button>
</div>
</div>
</div>
```
Bug reason is that `crawlSiblingsUp` had a wrong same node check on el and sibling. So when `x-trap` node have a parent node, focus would not trap.
Tests were not good enough to check the case, so tests are now improved.

fixed #1959 #1962 x-trap crawl bug

---

packages/docs/src/en/plugins/trap.md

Add a whitespace before the closing the curly brackets.

Fix formatting for x-trap plugin

---

packages/alpinejs/src/directives/x-init.js
tests/cypress/integration/directives/x-init.spec.js

This PR
- adds a check on `x-init` expression to skip `evaluate` if it's empty. 
This will allow server side conditional `x-init` expressions rendering such as:
```html
<div x-init="@if ($initialExpression) .... @endif">...</div>
```
Mentioned: 
- #1991

Fix empty x-init

---

packages/persist/src/index.js
tests/cypress/integration/plugins/persist.spec.js

When using $persist(...).as, the alias is currently applying to all the next $persist calls rather than just the current one.
For example https://codepen.io/SimoTod/pen/XWgmJqZ
After changing the first value and refreshing the page, the update is applied to the second one despite having a different name. If you inspect localStorage, you can see that only one key is saved (the one using the alias).
This PR moves the local variable to the right scope so it doesn't conflict with other $persist calls 
Failing test case: https://github.com/SimoTod/alpine/runs/3447390431#step:6:958

Bug with $persist.as

---

packages/alpinejs/src/utils/on.js
packages/docs/src/en/directives/on.md
tests/cypress/integration/directives/x-on.spec.js

Built a simple calculator demo last night. Ran into two obvious key issues:
`@keydown.window..=` is not valid Alpine syntax 
`@keydown.window.==` is not valid HTML 
This PR solves both issues by introducing:
1. `@keydown.window.period=`
2. `@keydown.window.equal=`

Add period and equal  directives

---

packages/trap/src/index.js

This PR fixes a bug caused by #1965 fix when using it with Livewire `@entangle ` .
Mentioned:
- #1983 
- #1982
- #1959 
Livewire `@entangle ` creates a bug on the Alpine components where parent node of the `x-trap` element is become a `document-fragment`. Just added `el.parentNode ` check on el to fix this.

Fixed shadow dom parent issue

---

packages/docs/src/en/directives/if.md

Currently the docs do not mention the fact that `<template>` tags can only contain one root element, specifically when used with `x-if`. I've added a small point of clarification that may help those wondering why only the first element in the tag is showing.
Added the following to the end of the file:
> Remember: `<template>` tags can only contain one root level element.

Adds clarification to x-if page in docs

---

packages/alpinejs/src/scope.js
packages/alpinejs/src/utils/walk.js

Add check to ensure ShadowRoot exists so Alpine V3 loads for older browsers (Chrome/Safari/Firefox when polyfills are present)

add ShadowRoot protection for older browsers

---

packages/alpinejs/src/directives/x-init.js

The change breaks `x-init` expressions that are defined via `x-bind` and possibly other
directives that pass an object through. It assumes the value of `x-init` will always be a string
(empty or not) by using the `trim` function.
The following still works after this change:
```
<div x-init="$nextTick(() => { console.log('this will be logged') })"></div>
```
But the following will now break:
```
<script>
const test = {
['x-init']() {
return this.$nextTick(() => console.log('this will not be logged'));
}
};
</script>
<div x-bind="test"></div>
```
Check the `expression` is a string before checking `trim` produces an empty string.

Fix `x-init` bug introduced in v3.3.0

---

packages/docs/src/en/upgrade-guide.md

When upgrading a project to v3, I got tripped up by this. Betting other folks will skip straight to the upgrade guide like I did and not realize that order matters with how v3 is initialized on the page. This is the only thing I've encountered so far! Perhaps some background about why this is deprecated would also be useful? 
Is it deprecated because it's better to have these data functions scoped within Alpine, or do you expect the old (global) functions to no longer work in a future version?
Thanks! ✌️

Updated docs - order matters w/ Alpine.data

---

packages/alpinejs/src/lifecycle.js
tests/cypress/integration/directives/x-init.spec.js

When x-init is defined on an element without x-data and that element has child components (other x-data's. x-init's or both), those children are initialised twice. The reason is that x-init will initialise the component and all children but outNestedComponents only checks for parent components having x-data to skip the duplicated call.

Bug - Components initialised twice

---

packages/alpinejs/src/directives/x-transition.js

Quite a few users mentioned that 3.4.4 broke their app when using x-show + click.away.
Annoyingly, the code did pass the test (https://github.com/alpinejs/alpine/blob/main/tests/cypress/integration/directives/x-on.spec.js#L353) but the exact same example loaded on a page is broken (https://codepen.io/SimoTod/pen/OJgQmba) 🤷 
I checked the reason for the fix (navigating to different tabs) and setTimeout won't pause like requestAnimationFrame so it should be fine plus is consistent with what we do in x-show (https://github.com/alpinejs/alpine/blob/main/packages/alpinejs/src/directives/x-show.js).
Closes #2080

Fix click.away regression

---

packages/alpinejs/src/directives/x-transition.js
tests/cypress/integration/directives/x-transition.spec.js
tests/cypress/utils.js

It seems that the fix for click away broke x-transition when they are defined in nested x-show.
setTimeout has a lower priority so the microtask for the transition start before the parent div gets showed and before the property change happens when the div is still hidden, the browser won't show any fancy effect. :(
I tried 'let clickAwayCompatibleShow = () => Promise.resolve().then(show)' and 'let clickAwayCompatibleShow = () => queueMicrotask(show)'. Both work correctly with the nested transition but do not work with clickAway
I tried
```javascript
let clickAwayCompatibleShow = () => setTimeout(show)
let nestedTransitionCompatibleShow = () => setTimeout(() => el._x_transition.in(show))
if (value) {
el._x_transition
? nestedTransitionCompatibleShow()
: clickAwayCompatibleShow()
return
} …
```

Bug - Another regression 

---

package-lock.json
packages/trap/package.json
packages/trap/src/index.js

This PR
- replaces `wicg-inert` with `focus-trap` plugin to introduce new approach to prevent focus bouncing to address bar when focus is trapped. 
This has been mentioned 
- #2057 ,discord and a tweet replay of mine. 
P.S.
I think this approach is cheaper and performs better since it does not need to crawl the dom to add or remove attributes.

refactored x-trap to use focus-trap plugin

---

packages/docs/src/en/magics/dispatch.md

changed a who's (possesive) to whos and an it's (possesive) to its.

Updated incorrect apostrophes in dispatch.md

---

packages/docs/src/en/directives/on.md

X-on cannot listen to events with upper case characters in their names. Added a line in the documentation to mark this and to reference why.
Info taken from the answer to this question: https://github.com/alpinejs/alpine/discussions/2215#discussioncomment-1469125

Add documentation note that x-on events are case insensitive.

---

packages/collapse/src/index.js
tests/cypress/integration/plugins/collapse.spec.js
tests/cypress/manual-transition-test.html

Currently, `x-collapse` will always set `overflow: hidden` to the element. This can give unwanted side effects.
This PR addresses possible issues by only setting `overflow: hidden` when it's strictly needed and defaulting to default value otherwise.
I tried to add a full integration test (check overflow:hidden, click button, see it's still there during transition, wait for transition to complete, check it's now gone) but I couldn't get that to work. Someone with more experience in Cypress might be willing to lend a hand here?
Fixes #2207 
Fixes #2208

x-collapse: only set overflow:hidden when strictly needed

---

packages/docs/src/en/upgrade-guide.md

AlpineJS has `$root` magic implemented in the core. Therefor it is not necessary to define a custom one.
This makes the upgrade vom v2 even smoother.

Make the upgrade from v2 easier

---

tests/cypress/integration/plugins/trap.spec.js

The test is failing on master because it assumes that the scrollbar width is 0 but it's not the case if the test runs on a real browser.

Fix x-trap test

---

packages/persist/src/index.js
tests/cypress/integration/plugins/persist.spec.js

While the magic returns a new instance every time (so alias and storage are scoped in that function call), the global persis was just returning the same function scope once so each usage of Alpine.$persist was sharing alias and storage.
See https://github.com/alpinejs/alpine/discussions/2317 where only the last value was persisted.
This PR changes the global property to a getter so we can return a fresh function scope every time.
In the future, if there are more global helpers like this one, it might be worth having something like `Alpine.addGlobal('persist', persist)` to abstract the getter so it's easier for people to use it.
Tests are failing because they are broken in master (something wrong with x-trap) but the relevant one is …

Bug - Alias for global persist shared between different properties

---

packages/docs/src/en/essentials/lifecycle.md

I found it confusing that the lifecycle event sections were named `Alpine.event` instead of just being named after the event (`alpine:event`). This PR names the sections after the event they document instead.

Name lifecycle event sections after event name

---

packages/docs/src/en/plugins/trap.md

In the example you forgot to add the `.inert` modifiers to `x-trap`.
I also added an `x-data` attribute to the body element. (This is just my opinion and I can also remove it.

[Docs] Fix inert example in x-trap

---

packages/alpinejs/src/mutation.js
tests/cypress/integration/mutation.spec.js

This is mostly an issue with third-party libraries such as phoenix livewire which trigger complex mutations in certain scenarios, causing x-data scope to be multiplied, duplicate event listeners, x-init to run multiple times, etc.
Basically, they trigger multiple mutations containing the same components so alpine runs initTree multiple times by mistake.
This Pr leverage the existing _x_ignore functionalities to skip any redundant processing.
Failed test: https://github.com/SimoTod/alpine/runs/4211546805?check_suite_focus=true#step:6:900
After fix: https://github.com/SimoTod/alpine/runs/4211553560?check_suite_focus=true#step:6:900

Fix components instantiated twice because of complex mutations

---

tests/cypress/integration/plugins/collapse.spec.js

Just an additional test to prevent future regressions.
The bug was already addressed by #2339
Branched off 3.5.0 to confirm that the test was failing as expected (see https://github.com/SimoTod/alpine/runs/4198418042?check_suite_focus=true#step:6:927then) then merged 3.5.1 into this PR to confirm that the test passes.

Test for x-collapse double click bug

---

packages/collapse/src/index.js
tests/cypress/integration/plugins/collapse.spec.js

Big fan of Alpine! Thanks for all the time that has been put into it :) 
I was checking out [x-collapse](https://alpinejs.dev/plugins/collapse) and noticed that visually collapsed content is not hidden/removed from the accessibility tree, so keyboard users can tab to focusable elements that should be hidden, and the content may be announced to screenreader users.
At the moment we just hide content with `overflow: hidden; height: 0px;` but this isn't enough to hide content from assistive tech.
One way to hide the content safely would be to add a `hidden` attribute after the transition has ended and the content has been collapsed (or add it on load), and remove the attribute before un-collapsing the content.
The `hidden` attribute approach is particularly nice as it will play nicely with …

Use the hidden attribute & `display:none` to hide x-collapse content from the accessibility tree

---

tests/cypress/integration/plugins/collapse.spec.js

The test was written before #2353 so it has to consider the addition of `display: none` now

Update test following #2353

---

packages/alpinejs/src/evaluator.js
tests/cypress/manual-memory.html

Fixes #2126 
The issue is that generateEvaluatorFromString stores a reference to the latest operation into the cached entry after the function has run. This causes leaks when the element is removed from the DOM because the cached entries keep dangling reference to alpine scopes.
`func.result` is already set to `undefined` at each execution on this line https://github.com/alpinejs/alpine/blob/main/packages/alpinejs/src/evaluator.js#L86 so setting it to `undefined` after the function has run won't change any existing behaviour. All tests are passing.
Since it's not testable in cypress, I've added a manual test for it. Feel free to checkout b2a19dcc0be9ccf8e42a9c9d908acd7bf7dea0be first to have a play.
There are other leaks to fix but I believe it's safer to just fix them one by one for each …

Misc - Fix evaluatorMemo memory leak

---

packages/docs/src/en/plugins/morph.md

The current implementation relies on Alpine being available on the window object.
Whilst that line was optional for other plugins, it's a required step for this specific one when using npm

Update morph documentation

---

packages/alpinejs/src/directives/x-for.js
tests/cypress/integration/directives/x-for.spec.js

Fixes #2210
If the root child of `x-for` uses `x-if`, the generated nodes were rendered at reverse because the loop pointer didn't move to the correct last item.
There was also an issue when reordering those nodes because the generated elements were not moved with the linked template tag.

Wrong order when x-for children use x-if

---

packages/docs/src/en/plugins/trap.md

Since #2072 the address bar can intentionally not be reached, we need to update the docs though.
While I was in this file I've also replaced usages of the word `dialogue` with `dialog`. Dialogue usually refers to speech, e.g. dialogue in a film or TV show, and dialog is the technical term used for a popup window. We can see the spelling dialog being used in ARIA (https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role) and in HTML (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog)

Remove mention of being able to access the address bar in `trap.md`

---

packages/alpinejs/src/directives/x-teleport.js
packages/alpinejs/src/lifecycle.js
packages/docs/src/en/directives/teleport.md
tests/cypress/integration/directives/x-teleport.spec.js
tests/cypress/integration/plugins/morph.spec.js

This PR fixes some typos that caught my attention in the recent refactor from x-portal to x-teleport.

Fix some teleportal typos in comments, tests and documentation.

---

packages/docs/src/en/directives/teleport.md

`x-teleport` was still called a plugin.

Remove plugin reference from teleport doc

---

packages/alpinejs/src/utils/styles.js

```
<body x-data="{ tab: 'si' }">
<nav>
<ul>
<li><a @click.prevent="tab = 'ai'" :style="tab == 'ai' ? 'text-decoration: underline;' : 'text-decoration: inherit;'" href="#">AI</a></li>
```
`
Unknown property 'null'. Skipped to next declaration.`

Firefox: Avoid warning "Unknown property 'null'. Skipped to next declaration."

---

packages/docs/src/en/directives/on.md

Just added some info confirming that `.throttle` can use the same duration modifier as `.debounce`. This functionality was implied by throttle's similarity to 'debounce', but now it's explicitly mentioned, avoiding any confusion.

Add info about modifying throttle duration

---

packages/docs/src/en/directives/transition.md

I'm not sure what Tailwind version you're running on the docs so I kept them in the Verbatim section.

Docs: `transform` utility is now redundant in Tailwind

---

packages/docs/src/en/directives/teleport.md

The `x-teleport` docs reference the selector as working like `document.querySelector`, but for anyone who is unfamiliar with that function, the examples only show it working on the `<body>` element.
This modifies the examples to demo the different selector types: tag, id, and class. I also added a link to the `querySelector` docs and expanded the explination to mention the CSS selector.
Note, I haven't tested my changes to the demo code as I don't have the docs running locally. If there is an easy way to do so, let me know and I'll happily test. I couldn't see anything in the repo about how that works though.

Explain querySelector usage in x-teleport docs

---

packages/docs/src/en/directives/teleport.md

Grammatical correction - its not it's

Remove single quote under Forwarding Events

---

packages/collapse/src/index.js
tests/cypress/integration/plugins/collapse.spec.js

As highlighted by #2409, there is a sporadic bug when transitioning out an element.
This seems to be more frequent with slow devices or when the CPU is busy: after collapsing an element, sometimes the full content shows briefly and then disappears again.
This has probably been introduced by removing `overflow: hidden` when an element has been expanded. When we are about to collapse the element, the element starts without that rule which gets set by Alpine in the transitioning phase.
The cleanup callback will then remove that property so, to retain it, we set it again in the complete callback.
Because the complete callback runs before the cleanup one, the code uses nextTick to introduce a small delay: this means that there is a short period when the element is fully collapsed, still …

Bug - x-collapse flickering

---

packages/alpinejs/src/magics/$watch.js
packages/docs/src/en/magics/watch.md
tests/cypress/integration/magics/$watch.spec.js

This PR enables deep watching by default. JSON.stringify(value) will touch any single property (or element for arrays) so they'll get picked up by the reactivity framework.
Pending questions before merging:
VueJs doesn't offer it by default but it has a deep flag. To me, it makes more sense to just make it deep by default which is what most of the users asked for, I think. However, I'm happy to introduce the flag if we think it's better, either defaulted to false like VueJs or to true.
If the watcher changes a different property on the same object, it will trigger an infinite loop, should we introduce a control variable to pause the watcher during the change?

Feature - deep $watch

---

.gitignore
tests/cypress/integration/directives/x-on.spec.js

I found that we are not running all the tests, because of the `test.only`.
I think it was added during development, but by mistake, it is merged to the main branch.
Before:
After:
PS. I was thinking to add eslint to prevent this kind of issue, but if you will agree to it I will add it in the next PR.

Remove .only from x-on.spec

---

packages/docs/src/en/directives/teleport.md

Changed `x-template` to `x-teleport` as `x-template` is not a directive and the line talks about `x-teleport`'s selector.

Change wrong directive name in docs

---

packages/morph/src/morph.js
tests/cypress/integration/plugins/morph.spec.js
tests/cypress/utils.js

patchChildren uses `firstChild` to select the first child node which works correctly with DOM elements and text nodes but then it uses `nextElementSibling` to get the next node which only returns DOM elements. As a consequence, if the children list is a mix of DOM elements and text nodes (for example, a paragraph content with `<br>` tags), any text node that is not the first child will be ignored and left in the previous status.
Flagged by #2463
Failing test: https://github.com/alpinejs/alpine/runs/4619366189?check_suite_focus=true#step:6:1106

Bug - Morph text nodes.

---

packages/docs/src/en/plugins/focus.md
packages/focus/src/index.js
tests/cypress/integration/plugins/focus.spec.js

There may be scenarios where you don't want to return the previous focus state after `x-trap` evaluates to false.
Consider a dropdown that is triggered by focusing a search input. If focus is returned to the input after closing the dropdown, it would just trigger the dropdown to open again.
A new modifier `x-trap.noreturn` would prevent this behavior.

Add noreturn modifier to x-trap

---

packages/alpinejs/src/utils/styles.js
tests/cypress/integration/directives/x-bind-style.spec.js

Fix binding style attribute with CSS variables

---

packages/docs/src/en/plugins/intersect.md
packages/intersect/src/index.js

`x-intersect` doesn't currently reliably work.
See #1833, #1871.
I can verify those experiences. Sometimes you can scroll an element into view, and the expression doesn't fire.
Next, #1933 added `x-intersect:leave` (yay) and `x-intersect:enter`, which was an implied alias (though the docs didn't acknowledge this explicitly) with one key difference: it works.
The problem is that the `IntersectionObserver` handler bails on the following three conditions:
```js
! entry.isIntersecting && value === 'enter'
|| entry.isIntersecting && value === 'leave'
|| entry.intersectionRatio === 0 && ! value
```
The first two are fine. The last one is no good. `intersectionRatio` is a tricky beast, and receiving a `0` doesn't mean that the element isn't visible. Since Alpine is supplying a `threshold` of …

Fix x-intersect reliability

---

packages/docs/src/en/directives/teleport.md

Came across this inconsistency on the docs page, where the rendered example does not match the example code.
Not _very_ confusing... but a little confusing.

Docs - fix x-teleport modal example

---

packages/focus/src/index.js
tests/cypress/integration/plugins/focus.spec.js

If the focus trap is active and the element is removed from the dom, focus doesn't get released and tabbing around the page becomes impossible. This happens in Alpine if the focus is combined to x-if.
```html
<div x-data="{ open: false }">
<button @click="open = true">open</button>
<template x-if="open">
<div x-trap="open">
<button @click="open = false">close</button>
</div>
</template>
</div>
```
Before https://github.com/alpinejs/alpine/pull/2556/files this was coincidentally working because the effect wasn't released correctly but it doesn't work anymore in v3.9.0

Focus trap doesn't release focus when the element is removed from the dom

---

packages/morph/src/morph.js
tests/jest/morph/external.spec.js
tests/jest/morph/hooks.spec.js
tests/jest/morph/internal.spec.js

The morph tests do not account for the morph function now being asynchronous. This PR is an attempt to remedy that.
That said, this PR seemed to have revealed a false positive in the test [`non-keyed elements are replaced instead of moved`](https://github.com/alpinejs/alpine/blob/aa2f5f2530b2c80755ff911f51889f1eb79089bb/tests/jest/morph/internal.spec.js#L14). I'll try and figure out what's going on at a later date.

Fix failing tests - account for the morph function now returning a promise

---

packages/morph/src/morph.js

When implementing the Morph plugin in Livewire, Livewire's tests were using an old version of Alpine, as such were getting the below error.
This PR ensures `Alpine.closestDataStack` exists, before using in the Morph plugin, as it wasn't introduced until 3.5.2.
Didn't add a test for it, as wasn't sure how to run a test using an older version of Alpine in Cypress.
Hope this helps!

Ensure `Alpine.closestDataStack` exists

---

packages/morph/src/morph.js
tests/cypress/integration/plugins/morph.spec.js

When morphing inline elements, Morph is currently adding a space before the "!" in the test.
With this as the starting from and to elements:
Running morph results in this:
This PR adds a failing test for this use case.
It also removes the `.only` left on the previous morph testcase.
I have some ideas on why this is happening so will have a play with it.
Hope this helps!

Fix Morph missing next sibling when replacing element

---

packages/morph/src/morph.js
tests/cypress/integration/plugins/morph.spec.js

This adds a Morph test for swapping two elements with different keys and updates the debugging breakpoint comment.
Hope this helps!

Add Morph test for swapping keyed elements

---

packages/morph/src/dom.js
packages/morph/src/morph.js
tests/cypress/integration/plugins/morph.spec.js

When running `Alpine.morph()` immediately after another `Alpine.morph()` call, because they are async, they run in a pseudo-concurrent way. Due to the use of global variables, the second run overrides the first one altering the result of the first morph call, see https://codepen.io/SimoTod/pen/vYpKmVZ (expecting 1-2 but getting 2-2).
To make sure that variables are not shared I moved them and most of the functions inside the morph function itself. It could probably be refactored to be a class but I didn't want to make the review more complicated so I changed as little as possible (git is already a bit rubbish at showing this kind of diff, it's probably easier to pull the file locally and compare it with the current version with a split editor).

Bug - Multiple morph calls clash 

---

scripts/build.js

This reduces the build size of the AlpineJS module by ~20%
AlpineJS
Before: 112kb
After: 87kb
Focus Plugin:
Before: 32kb
After: 28kb
I've used a variation of this build myself on projects for a while now and have yet to see any actual issues in browser or with bundlers.

Swap mainfields in build script

---

packages/alpinejs/src/directives/x-for.js
packages/alpinejs/src/directives/x-html.js
tests/cypress/integration/directives/x-for.spec.js

Currently, for newly created elements, the initTree callback is inside a mutate dom call which means that directives injected by `x-html` are not picked up by the mutation observer. It shouldn't be a big issue to move initTree outside of mutateDOm as we do for refreshScope when dealing with elements that are shuffled around.

X-html in x-for

---

packages/docs/src/en/directives/transition.md

I noticed an error in the `x-transition` directive documentation: the `.duration` modifier currently handles both `enter` and `leave` durations.

Fix x-transition documentation

---

packages/alpinejs/src/utils/on.js
packages/docs/src/en/directives/on.md

This PR adds a named key to `packages/alpinejs/utils/on.js`.
Analog to `.` (Period) and `=` (Equal), html attributes may also not contain the `/` ((Forward-Slash) character.

Added forward-slash named keyboard event

---

packages/alpinejs/src/nextTick.js
packages/docs/src/en/magics/nextTick.md

To bring the functionality more inline with [Vue's implementation](https://v2.vuejs.org/v2/api/?redirect=true#Vue-nextTick) of `$nextTick`, the magic returns a Promise that resolves when the callback is run.
This allows pausing your own functions until after pending DOM updates without needing to handle your own scheduling.
Shouldn't break anything since nobody should be assigning the output of `$nextTick` to anything anyway.
Side Story:
I was having issues with the reactivity related to an array between two components where the last update to the array would not be reflected in the DOM (and one or two other similar things) and I dove into the Vue reactivity docs and they mentioned using `$nextTick` when there are rendering issues, and I tried it and it worked for Alpine, even without the …

Add Promise to $nextTick

---

packages/docs/src/en/directives/bind.md

based on the current documentation I was trying to setup an `x-ref` via a binding with 
```js
trigger: {
['x-ref']() {
return 'trigger';
},
},
```
which does not work.
After some trial and error I got it to work with 
```js
trigger: {
['x-ref']: 'trigger',
},
```
so I figured I'd add it to the docs so no one needs to struggle like I did 😄

add `x-ref` binding example

---

packages/docs/src/en/magics/store.md

currently Alpine.store(...) links to /magics/store, which is counter intuitive, hence change the like to the actual  Alpine.store(...) docs at  /globals/alpine-store

change "Alpine.store(...)" link to /globals/alpine-store

---

packages/focus/src/index.js
tests/cypress/integration/plugins/focus.spec.js

Currently, when using `x-trap`, the first child element in the tab order is focused per the `focus-trap` package defaults. This pull request adds a more sensible default by focusing the first element that has the `autofocus` attribute. If none is found, the first child element in the tab order is focused.
I could see this being especially helpful in the context of modals and drawers.

Adds autofocus awareness to the focus plugin

---

packages/alpinejs/src/directives/x-transition.js
tests/cypress/integration/directives/x-show.spec.js

This fixes a bug where multiple consecutive state changes in a short time cause x-show to update the DOM in an inconsistent way so that elements that should be hidden are visible. Demo: https://codepen.io/mgschoen/pen/XWZqprb 
This is caused by using `requestAnimationFrame` or `setTimeout` for the `show()` method, but `queueMicrotask()` for the `hide()` method, causing `hide()` calls from multiple state updates to be fired before the first `show()` call, effectively showing elements that should actually be hidden.
This bug has also been reported in https://github.com/alpinejs/alpine/issues/2803#issuecomment-1126751072

Fix x-show updating DOM inconsistently if state changes too fast

---

packages/mask/src/index.js
tests/cypress/integration/plugins/mask.spec.js

Hi,
I have a specific use case for the Mask plugin, where the user selects an international phone code and the input value gets formatted accordingly.
However, the user should also have an option to type the number without being forced the format (in a case, the format is not available in the list). Example:
In the end, the example code looks like this:
```
x-mask:dynamic="selectValue ? `${options[selectValue].international} ${options[selectValue].format}` : false"
// Above translates to:
x-mask:dynamic="'cz' ? `+420 999 999 999` : false" --> +420 987 654 321
// Or:
x-mask:dynamic="null ? `` : false" --> no forced formatting
```
And that's what this PR allows for. Let me know if anything needs changing.

Allow disabling x-mask with a `falsy` value

---

packages/docs/src/en/directives/on.md

.meta does not map to the `ctrl` key on Windows.

Clearing up .meta confusion

---

packages/morph/src/dom.js
tests/cypress/integration/plugins/morph.spec.js

This changes the Morph plugin to use createElement('template').content rather than createRange().createContextualFragment() as the later does not support table `<tr>` or `<td>` tags as the root element.
Morphing individual rows in a table is a common use case as a "row" is often a "component" in a component oriented backend framework.
See https://github.com/alpinejs/alpine/discussions/3019

Change Morph plugin to use createElement('template').content for crating DOM fragments, this enables table <tr>/<td> support.

---

packages/alpinejs/src/directives/x-show.js
packages/docs/src/en/directives/show.md
tests/cypress/integration/directives/x-show.spec.js

Following up on [this discussion](https://github.com/alpinejs/alpine/discussions/1415).
There are cases where someone may use a class which itself sets the `display` property. If it is set with the `!important` property `x-show` stops working as expected because the class will always take precedence.
This PR adds an `.important` modifier to `x-show` which sets the inline style with `!important` itself.
I've added a test and updated the docs, please let me know if there are other changes needed :)

Allow for using x-show with an important modifier

---

packages/docs/src/en/directives/for.md

The `x-for` page in the docs could be more clear.
It would be clearer to say that a template element "MUST contain" rather than "MUST have only one root element".
I have also standardised the way that the caveats are presented to bring them in line with the format of the `x-bind` page.
I have also added an example of what will and will not work in terms of contents of a `<template>`

Clarify for.md in docs

---

packages/alpinejs/package.json
packages/collapse/package.json
packages/focus/package.json
packages/history/package.json
packages/intersect/package.json
packages/mask/package.json
packages/morph/package.json
packages/persist/package.json
packages/ui/package.json

This allows IDEs and NPM to guide users towards relevant documentation.
For example, using the `npm docs alpinejs` command or hovering over the dependency in VSCode.
Looks like test failed from some incomplete code elsewhere.
Additionally, this adds repository information for use by various other tools (addressing: https://github.com/alpinejs/alpine/discussions/3147 )

:memo: Provides more information in package.json

---

packages/docs/src/en/plugins/mask.md
packages/mask/src/index.js
tests/cypress/integration/plugins/mask.spec.js
tests/jest/mask.spec.js

x-mask: Allow overriding thousands separator

---

index.html
packages/alpinejs/src/directives/x-model.js
tests/cypress/integration/directives/x-model.spec.js

If an element using x-model is included in a form and the form provides a reset button, clicking said button will desync the UI from the alpine state (all input elements get emptied but the Alpine scope won't see the update).
Failing test before fix: https://github.com/SimoTod/alpine/runs/8214754814?check_suite_focus=true#step:6:572

Form reset support for x-model

---

packages/collapse/src/index.js

Zoom levels other than 100% is returning 3 decimal points values for height compared to standard 2 decimal used in browsers. Thus the condition to remove overflow:hidden never becomes truthy as 92.312  == 92.31 => false

Fix issue #2208 x-collapse caused by zoom levels

---

packages/alpinejs/src/utils/on.js
tests/cypress/integration/directives/x-on.spec.js

Currently, the usage of a throttle modifier on a `keyup` or `keydown` event does not work. I took the ideas from @sterat's PR(#1911) and [discussion](https://github.com/alpinejs/alpine/discussions/1895) and applied the fix which was suggested by @SimoTod. 
This PR also includes a testcase which fails without the modification in the `x-on.js` file and passes with it.

Fixed throttling on keypress

---

packages/docs/src/en/directives/cloak.md

The `x-cloak` page in the docs is less clear than it could be.
At present it doesn't address the main cause of "blipping": where an element is hidden by `x-show` but momentarily blips onto the page on load.
This edit clarifies that by using `x-show` as the first example, but also including the existing example (where an element "blips" onto page before its contents is set.
It also moves the "alternative" approach to a global style to its own sub-section.

Clarify cloak.md in docs

---

packages/docs/src/en/plugins/intersect.md

This sentence is hard to parse, because some of the commas are for delineating the outer list of items, and some of them are internal commas.
Supercomma to the rescue!
https://www.thepunctuationguide.com/semicolon.html

Use supercommas to break up comma-containing list items

---

packages/alpinejs/src/utils/on.js
tests/cypress/integration/directives/x-on.spec.js

Addresses bug found in https://github.com/alpinejs/alpine/discussions/3124
This PR:
- Prevents `' '` and `'_'` from being coerced into `'-'` in the `kebabcase` function.
- Adds test for these cases.
- Adds the modifier `minus` and `underscore` as aliases for `-` and `_` when using them as `@keydown` modifiers.
This will break any apps that actually depends on this coercion, but I don't think that would be an expected behavior that anyone would be relying on.

:bug: prevents coercion of space and underscore to minus

---

packages/alpinejs/src/directives/x-teleport.js
tests/cypress/integration/directives/x-teleport.spec.js

Sometimes it is needed to teleport a node after or before an existing node.
Example:
```html
<table>
<template x-for="n in 10">
<tr x-bind:id="`row-${n}`">
<template x-teleport:append="#row-5">
<tr>
<td colspan="2">EVERYTHING ABOVE 5</td>
</tr>
</template>
<td>#</td>
<td x-text="n"></td>
</tr>
</template>
</table>
```
The example above will add a new `<tr>` correctly
Especially when you deal with `<tr>`, you are hitting a problem here because you can only have one single root element within a `<template>`. Sometimes, you need to have a second one.
With `x-teleport:append`, you can append a node as a sibling of the target instead of a child. Works same wise with `x-teleport:prepend`

Introduce x-teleport values/modifiers

---

package-lock.json
packages/focus/src/index.js
tests/cypress/integration/plugins/focus.spec.js

Using `x-trap.inert` causes some extra recursion that I don't think is intended.
The `crawlSiblingsUp` function is working overtime and re-crawling elements that have already had `aria-hidden="true"` applied. This is even more apparent when there are tons of DOM elements, and it causes some significant performance problems in that case. The codepen below illustrates the problem in the console. 
**Codepen (see the console in codepen)**
https://codepen.io/austenc/pen/XWYxeoB
When the button is clicked, the console produces four log lines:
I'm not sure how to write a test for this recursion case. Perhaps we could do something similar to the codepen with mutation observer to check those sibling elements are only mutated once?
Any help on the tests is much appreciated!

Fix recursion problem with x-trap inert

---

packages/alpinejs/src/scheduler.js
tests/cypress/integration/directives/x-if.spec.js

This PR implements a fix for a bug in which some `template x-if` elements are rendered inconsistently; 
i.e. given two `template x-if` with an identical condition, one is shown while the other is not.  
This is a reproducible bug discussed in [Discussion #2802](https://github.com/alpinejs/alpine/discussions/2802) and in [Issue #2803](https://github.com/alpinejs/alpine/issues/2803). Based on the CodePen posted in the Issue thread, I prepared a minimal reproducible example: https://codepen.io/ferranconde/pen/OJEzeLL?editors=1000
According to [this comment](https://github.com/alpinejs/alpine/issues/2803#issuecomment-1128658513), the bug arises from the interaction of `flushJobs()` and `dequeueJob()` in `scheduler.js`.  
Given a tag `<template x-if="condition">`, if `condition` becomes …

Fix inconsistent update for template x-if (issue #2803)

---

packages/alpinejs/src/evaluator.js
packages/alpinejs/src/scheduler.js

Alpine.js executes reactive effects when the application state changes. Some of these reactive effects involve executing
custom methods defined by the application developers (e.g. methods for `x-show`, `x-text`) and thus may contain bugs.  
When one of these callbacks raises an unexpected exception, the whole application becomes unresponsive because Alpine does not handle this gracefully.  
In the following reproducible example (https://codepen.io/ferranconde/pen/PoaQJaX?editors=1010), 
there's a component whose `x-show` method features a faulty implementation.  
After clicking on the orange button, any other component, e.g. the counter text + button, stops working: the application is in an unrecoverable state.
The issue is that, in `scheduler.js:flushJobs()`, if there is an uncaught …

Fix Alpine.js becoming unresponsive after uncaught exception in reactive effect callback

---

packages/docs/src/en/advanced/csp.md

As a newcomer considering Alpine.js for a project, I found it very confusing that the CSP build’s documentation makes it sound like it’s available to use now even though it’s not published on npm. This PR makes minimal changes to the page to clarify this, and provide guidance on what people should do in the meantime.
The info I added is based on https://github.com/alpinejs/alpine/issues/237#issuecomment-999692410 – there might be more details that could be added here that aren’t publicly available (see also https://github.com/alpinejs/alpine/discussions/1944).

Update CSP documentation to clarify availability of the CSP build

---

packages/alpinejs/src/directives/x-data.js

As per #3337, some frameworks (like htm) convert `<div x-data … />` to `<div x-data="true" … />` whereas Alpine.js currently only accepts the equivalent of `<div x-data="" … />`. This patch (based on https://github.com/alpinejs/alpine/discussions/3337#discussioncomment-4397836), also makes it accept `x-data="true"` to mean data is `{}`.

Accept x-data="true" as a synonym for x-data="{}"

---

packages/docs/src/en/advanced/extending.md
tests/cypress/integration/plugins/navigate.spec.js

There are small typos in:
- packages/docs/src/en/advanced/extending.md
- tests/cypress/integration/plugins/navigate.spec.js
Fixes:
- Should read `specifying` rather than `specifing`.
- Should read `piece` rather than `peice`.
- Should read `persistent` rather than `persistant`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

packages/alpinejs/src/clone.js
packages/alpinejs/src/directives/x-model.js
tests/cypress/integration/clone.spec.js

The `x-model` directive's event listeners are getting registered **twice** when an element is cloned with `Alpine.clone()`.
This happens once via `initTree()` when clone walks the DOM initializing stuff. Secondly, the mutation observer picks up on `x-model` and then registers the listeners again. A couple other things:
- Only noticeable when `x-model` is bound to an array (i.e. checkboxes), but seems to happen for any input with `x-model`.
- Affects Livewire in particular, due to it cloning Alpine components when making DOM updates. livewire/livewire#5454.
- Tried writing a test for the event doubling on any input, but doesn't seem like JS has a native way to retrieve a list (or count) of attached event listeners.
- This line doesn't feel great... thoughts? …

Fix x-model event listener doubling when cloned

---

packages/alpinejs/src/utils/on.js
packages/docs/src/en/directives/on.md
tests/cypress/integration/directives/x-on.spec.js

When added to a `@keyup` or `@keydown` event listener, the `.capture` modifier is currently interpreted as a keycode, e.g. the listener is never executed.
Reproduction of the current bug: https://codepen.io/mgschoen/pen/PoBBVMX
This PR
- fixes that `.capture` also works with `keyup` and `keydown` events
- extends `.capture` tests accordingly
- adds docs for `.capture`

Fixes @keyup and @keydown listeners with .capture modifier never executed

---

packages/alpinejs/src/directives.js

`Array.prototype.indexOf` returns `-1` when an item is not found, which would never utilize the nullish coalescence.
To satisfy the apparent intent, this instead simply uses a ternary in the target index of splice
@SimoTod

:bug: fixes improper use of nullish coalescing

---

package-lock.json
package.json
scripts/build.js

Bumps esbuild to `v0.16.17`. Does not bump to the latest, as `v0.17.x` introduces a new way to do watch mode. I'm thinking that update can be done separately. `v0.16.17` should introduce some enhancements for Alpine, including the  `packages` option, which will provide an easy way to allow non-CDN bundles to exclude bundling `npm` packages.
See somewhat related discussion [here](https://github.com/alpinejs/alpine/discussions/3434).
These are the changes to the build output sizes, based on my local machine.
<details>
<summary>Before</summary>
```
alpinejs: 13.5 KB
collapse: 570 Bytes
csp: 13.5 KB
focus: 3.7 KB
history: 415 Bytes
intersect: 463 Bytes
mask: 865 Bytes
morph: 1.4 KB
navigate: 9.7 KB
persist: 327 Bytes
ui: 11.8 KB
```
</details>
<details>
<summary>After</summary>
```
alpinejs: …
```

Bump esbuild from 0.8.39 to 0.16.17

---

packages/docs/src/en/plugins/mask.md
packages/mask/src/index.js
tests/cypress/integration/plugins/mask.spec.js

Allows for custom decimal precision using x-mask $money magic as requested here: https://github.com/alpinejs/alpine/discussions/2873
Example usage:
- To allow for a decimal precision of 3 digits: `<input x-data x-mask:dynamic="$money($input, '.', ',', 3)">`
- To only allow for round numbers: `<input x-data x-mask:dynamic="$money($input, '.', ',', 0)">`
It defaults to 2, so the current behaviour without specified precision should still be the same:
`<input x-data x-mask:dynamic="$money($input)">`

x-mask custom decimal precision

---

packages/alpinejs/src/directives/x-model.js
packages/docs/src/en/directives/model.md
tests/cypress/integration/directives/x-model.spec.js

Set an x-model bound value to the value of the input when the bound value is null or an empty string, 
but as stated in the original discussion this might actually be expected default behaviour. 
The implementation is currently using a "fill" modifier (name subject to change) for now, but might be better as default behaviour with a modifier for the possibility of overwriting any non-nullish value as well, as suggested by @ekwoka (https://github.com/alpinejs/alpine/discussions/1985#discussioncomment-4957333)
Original request by @motine here: https://github.com/alpinejs/alpine/discussions/1985
**Example usage:**
```
<div x-data="{ myValue: null }">
<input x-model.fill="myValue" value="123456" />
</div>
```
**Result:**  
since `myValue` in the example is initially `null`, thanks to the …

x-model.fill by input value on null or empty string

---

package-lock.json
package.json
scripts/build.js

Replaces `brotli-size` with `node:zlib`. Tested, and both produce the exact same output.
> [`brotli-size` is] only used to indicate during building the current size of the bundled packages, so it has no actually effect.
> 
> `brotli-size` was a convenience package for compressing and displaying the size, while nodejs `zlib` is a core module that can brotli compress and then we can easily get the buffer size from there without involving third party code.
> 
> Here it looks like it's even an exact API match. So its just knocking off an unneeded dev dependency.
&mdash; @ekwoka ([source](https://github.com/alpinejs/alpine/pull/3449#issuecomment-1457698301))

Replace brotli-size with zlib

---

packages/alpinejs/src/magics.js

From https://github.com/alpinejs/alpine/issues/2847 :
> High frequency evaluations of alpine strings that use magics (requestAnimationFrame usage in our case) exacerbate a leak we have found.
> What we observe is that _x_cleanups will grow by 1 every time you use a magic property in an evaluated string, which will eventually cause our web page to crash running out of memory.
> Here is a minimal reproduction of the issue: https://codesandbox.io/s/alpine-memory-broken-mlip56?file=/index.html
> Resize the preview window on that page and you should see that _x_cleanups for the div with id "leaky" grows.
We have two thoughts about potential fixes for this behavior in `injectMagics` function:
1. To memoize the setup/cleanup mechanism to only run once, lazily evaluated.
2. To clean up the …

Attempt memory leak fix from using magics

---

packages/morph/src/dom.js
packages/morph/src/morph.js
tests/cypress/integration/plugins/morph.spec.js

This PR fixes an issue with morph, where if the key already exists in the DOM and is to be moved up during morph, it wasn't getting moved correctly.
The reason was, that `fromKeyDomNodeMap` was empty, so the `fromKeyNode` in the below snippet was always empty, so the move "from" key was never running.
https://github.com/alpinejs/alpine/blob/a9206161f0bf878d41a001197553613cf31cbde9/packages/morph/src/morph.js#L259-L265
Removing the commented out `keyToMap(fromChildren)` got it working, but then caused an infinite loop. This was due to `dom.replace()` replacing the old with the new, but leaving the new one in its place in the array, causing two references to the dom node. So then when any `dom.()` methods run and try to find the index of the node, there would be two of them but only the …

Morph key lookup issue

---

packages/alpinejs/src/directives/x-model.js
tests/cypress/integration/directives/x-model.spec.js

Addresses #3675 
Allows checkboxes modeled to an array to use `x-model.fill`
While other model.fill work based on the value being explicitly null, this applies regardless of the arrays length, so long as the modeled value is an array.

bug: Allows model.fill to work with checkbox arrays

---

package-lock.json
packages/focus/package.json
packages/ui/package.json
packages/ui/src/list-context.js

Before this, the `@alpinejs/ui` package included inside itself a whole other copy of `alpinejs` since it referenced the internal file, not through the module system. This causes a few issues during actual runtime.
This also fixes the long standing issue where `tabbable` was not actually available to the `focus` plugin.

:bug: Prevents double bundling of Alpine in UI Package

---

packages/docs/src/en/globals/alpine-data.md

Document the `destroy()` method of components on the docs page for `Alpine.data`. Includes an example allowing the reader to easily play and experiment with the behavior.

Document destroy method in Alpine.data

---

packages/docs/src/en/directives/init.md

there are multiple ways to run code on Alpine initialization, so this clarifies the order of execution of the object `init()` method vs the `x-init` directive.

clarify execution order of `init`

---

packages/alpinejs/src/directives/x-if.js

Added a warning if x-if is used on a tag other than template (similar to x-teleport warning).

x-if warning if used on non-template

---

packages/alpinejs/src/scope.js

This PR refactors `mergeProxies` to increase performance and reduce memory costs.
- :bug: Allows JSON stringifying $data (solving an issue presented in discord)
- :recycle: Uses Reflect (to reduce code and memory)
- :zap: Shortcircuits on unscopables (to increase performance on every access of data in expressions)
- :recycle: Extract proxyTraps (to reduce memory)
- :white_check_mark: Uses legacy syntax (to pass tests)

:recycle: improves merge proxies

---

packages/alpinejs/src/evaluator.js

This PR adds the expression as a name to the evaluator function. While Alpine logging information about the expression is helpful, many tools like sentry won't fully track or associate those warning logs with the actual error.
This change allows the expression to show as the name of the function in the stack trace itself making hunting down errors much easier.

:sparkles: Names expression evaluators

---

packages/morph/src/morph.js
tests/cypress/integration/plugins/morph.spec.js

This changes the morph markers that Alpine recognizes to match the ones in this Livewire PR: https://github.com/livewire/livewire/pull/6974
``
``
Read that PR for more details, but basically the issue is that some proxies strip HTML comments, which means that the morph markers that a backend like Livewire renders might get stripped by things like Cloudflare (with HTML minification on). The Internet Explorer conditional syntax above will be ignored by Cloudflare (and likely other HTML-minification pipelines) because historically it was used to enable or disable functionality on certain browsers.

Use Internet Explorer conditional comment syntax to preserve morph markers on Cloudflare-proxied sites

---

packages/morph/src/morph.js

Seems like this is an incorrect reference, since `_x_teleportBack` exists in the codebase but `teleportBack` does not.
Edit: Turns out it isn't even needed at all, and the typo is what was letting it not break.
Obligatory: TypeScript would have prevented this.

:bug: Fixes reference to incorrect attribute

---

packages/alpinejs/src/scope.js
tests/cypress/integration/scope.spec.js

Solves #3804 
This was a regression in the behaviors from the merge proxy optimization.
This still seems problematic in many ways. but this more faithfully represents the older logic.
If there is a getter setter pair, the `this` refers to the proxy stack. If it's just a setter, it doesn't (this was how the original logic worked).
Similarly to before, using getters/settings/methods,etc on the parent component can modify the child component when keys match. Not great, but that's how it has been.
It could be possible to instead limit it only to that level and parents, but that would change the behavior.
This also adds tests to ensure this continues to work :)

:bug: Fixes proxy stack setters bug

---

package-lock.json
packages/alpinejs/src/entangle.js
tests/cypress/integration/entangle.spec.js

Just improves the logical flow of entangle to clean out unnecessary operations.
The whole stringify/parse thing seems unnecessary and there is nothing in the history to indicate why it was ever needed (and it didn't even do it in all cases). Seems like an unexpected behavior to have it clone the objects, and not explicitly reference the same object. I definitely wouldn't understand why using modelable with an object would not share references...It was just always rerunning the entangle if a property changed.
But this also allows an initial outer value of `undefined` which did not work before.
It can be reintroduced to actually clone (and do it for all cases) pretty simply, if you remember why that was a wanted behavior.
In fact, don't even need the hash really, could just directly …

:recycle: Cleans Up Entangle

---

packages/persist/src/index.js

If an exception is thrown when trying to assign `storage = localStorage`, the persist plugin currently fails with an unhandled exception. In Sentry logs I'm seeing this occur occasionally (about once per day) with Safari 16.x on iOS, and the issue renders the application unusable for these users. Using custom storage with `$persist(0).using(customStorage)` doesn't solve the issue since the exception will still be thrown.
This pull request suggests using a variable object on `window` for temporary storage as an alternative to persistent storage when localStorage is unavailable. A message is logged to the JS console to indicate that the value is being stored only temporarily. This alternative handles the exception and makes the application usable, even though the value will not be persisted …

Gracefully handle SecurityError exception if localStorage is unavailable

---

benchmarks/giant.html
packages/docs/src/en/advanced/csp.md

use a standard single quote, which is common practice, and is consistent with the rest of the repo.

use normal single quotes

---

packages/docs/src/en/advanced/csp.md

there has been a lot of confusion on how to use the CSP build, so this commit hopefully clears them up, and provides more explicit instructions on how to "build from source".
some of the wording and code examples make it seem like an NPM package is available, so we'll update that to avoid confusion.

update CSP build/installation docs

---

packages/alpinejs/src/directives.js
tests/cypress/integration/directives/x-on.spec.js

Solves #3023 
Allowing underscores in event names
Test includes

:white_check_mark: Allows underscore in event names

---

packages/alpinejs/src/lifecycle.js

While an array of strings can work when the runtime chooses to coerce the array to a string, it is outside of the DOM spec, which allows only a string. Some DOM runtimes, like Happy-dom do not support selectors that are arrays.
This just brings the code inline with the spec.

:bug: Joins selectors to meet spec

---

packages/docs/src/en/directives/model.md

* Adds range input to examples in `model.md` documentation
I've been playing around with the range input type with AlpineJS and there seems to be no issue. It feels sensible to add it to the docs as a supported input type.

[Docs] Add range type to x-model inputs

---

packages/docs/src/en/directives/for.md

`x-for` also accepts objects in addition to arrays. the docs currently only mention arrays, so users might not be sure if objects are allowed. this explicitly states they are and gives an example how to use them.
I was trying to find the relevant PR for when this functionality was added, but was unable to. I found some PRs from Ryan Chandler that were trying to add this feature but were closed.

add explanation of passing an object to `x-for`

---

packages/mask/src/index.js

Hi,
Found a bug when using x-mask with Livewire. Problem is sometimes input changed by Livewire and mask directive intiated every time. Adding cleanup of event listeners fix this issue.
Unfortunately don't know how to make correct tests for this situation without LW part, but you can check it on this wirebox: https://wirebox.app/b/4kwle
To reproduce:
1. Fill both inputs with `12345` string
2. Click toggle button
3. Try to enter `6` (to get `123456` string) in both fields. First field has weird behaviour, second field is OK.
Second field has patched version of mask plugin.

x-mask: Cleanup of event listeners

---

packages/csp/src/evaluator.js
packages/csp/src/index.js
packages/docs/src/en/advanced/csp.md
packages/docs/src/en/advanced/extending.md
packages/docs/src/en/advanced/reactivity.md

This PR provides a version of AlpineJS that is compatible with strict content security policies that would otherwise prevent the usage of Alpine because of "unsafe-eval" violations.
It removes the ability to evaluate JavaScript expressions inside HTML attributes; however, it maintains ALL functionality of Alpine otherwise.
All plugins and features are CSP-compatible when using this build.

Add CSP-friendly Alpine build

---

packages/docs/src/en/plugins/anchor.md

The code example uses `#` in the `getElementById` function, which breaks the code
```js
// Wrong
document.getElementById('#trigger')
// Right
document.getElementById('trigger')
```
Full code example
```html
<div x-data="{ open: false }">
<button id="trigger" @click="open = ! open">Toggle</button>
<div x-show="open" x-anchor="document.getElementById('trigger')">
Dropdown content
</div>
</div>
```

Bug in code example of documentation for x-anchor to an ID

---

packages/alpinejs/src/utils/error.js

solves #3569 
Apparently some things out there might throw `undefined` or `null` causing the error handler to fail.
This just intercepts it and provides a default message in the event such a thing happens.

:bug: Gracefully handles bad throws

---

packages/ui/src/combobox.js
tests/cypress/integration/plugins/ui/combobox.spec.js

Currently when setting a default value for the combobox it isn't displayed right away. You would have to open and close it before the display value would be visible. This will reset the input as part of the init so the value is displayed right away.

fix: reset input on init so default value is displayed

---

packages/ui/src/combobox.js
tests/cypress/integration/plugins/ui/combobox.spec.js

Fixes https://github.com/alpinejs/alpine/discussions/3724
When you want to clear the selected value or you want to set the selected value via code, the search input is not immediately updated. You must click somewhere on the page to update the search input's value.
https://github.com/alpinejs/alpine/assets/22586858/69d491e9-e7b5-4e7c-a897-137876af613b
This PR fixes that. When the selected value changes, the search input's value immediately updates.
https://github.com/alpinejs/alpine/assets/22586858/5175a960-9e12-4952-b4ad-79184d968a29

Clear combobox bugfix

---

packages/alpinejs/src/lifecycle.js
packages/alpinejs/src/mutation.js

Currently we defined if a mutation is a move operation if the node is in the `addedNodes` and in the `removedNodes`. 
However in some case, an element is added, removed and added again. So it should considered as `add` + `move` operations. But alpine will ignore it, considering it as a move operation only (so nothing will be init).
The PR focus on introducing a new state `_x_isInit` that will be true for component that are initialized.
Also it may speed up a little bit the `onMutate` function. Previously we checked every deleted nodes before adding any new nodes. For big mutations, iterate over the `deletedNodes` several times could be CPU intensive.
> Conversation on : https://github.com/alpinejs/alpine/discussions/3947

fix: already init component

---

packages/ui/src/listbox.js
tests/cypress/integration/plugins/ui/listbox.spec.js

When there is no value selected and the `by` attribute is used, then an error occurs because it tries to access a property on `null`. This PR fixes that. I got the fix from the combobox.js file, as the issue was already fixed there.

Listbox compare null value bugfix

---

packages/docs/src/en/plugins/focus.md
packages/focus/src/index.js
tests/cypress/integration/plugins/focus.spec.js

Adds a new x-trap modifier: .noinitialfocus to trap focus without giving focus to the first element in the focus trap
Test included
Relates to discussion #2806
Use case is to be able to create a modal with the option of not focusing the first input. For example, Wire Element Modal is a Livewire component for creating modals, which uses x-trap, and currently has no mechanism (besides tricks like hidden inputs) to create a modal that opens without focusing its first input: [https://github.com/wire-elements/modal/discussions/367](https://github.com/wire-elements/modal/discussions/367)

Add x-trap noinitialfocus modifier

---

packages/ui/src/combobox.js
packages/ui/src/listbox.js
tests/cypress/integration/plugins/ui/combobox.spec.js
tests/cypress/integration/plugins/ui/listbox.spec.js
tests/cypress/utils.js

I created a listbox (or combobox) with options that are present in HTML and not generated by javascript.
```blade
<div>
<button wire:click="$refresh" type="button">trigger livewire update</button>
<div x-data="{ value: null }">
<div x-listbox x-model="value">
<button x-listbox:button>
Select Framework
</button>
<ul x-listbox:options>
<li :class="{
'text-blue-100': $listboxOption.isActive,
'text-yellow-100': !$listboxOption.isActive,
'!text-gray-60 opacity-50 cursor-not-allowed': $listboxOption.isDisabled,
}" x-listbox:option value="laravel">
Laravel
</li>
<li :class="{
'text-blue-100': $listboxOption.isActive,
'text-yellow-100': !$listboxOption.isActive,
'!text-gray-60 opacity-50 cursor-not-allowed': $listboxOption.isDisabled,
}" x-listbox:option value="rails">
Ruby on Rails
</li>
<li …
```

Combobox and listbox: Save optionKey in x-data to fix usage in Livewire

---

packages/alpinejs/src/mutation.js
tests/cypress/integration/mutation.spec.js

Fixes #3994
Introduced in #3951
Adds a test for it :)

:bug: Fixes reinitializing moved elements

---

packages/ui/src/combobox.js
packages/ui/src/listbox.js
tests/cypress/integration/plugins/ui/combobox.spec.js
tests/cypress/integration/plugins/ui/listbox.spec.js

In my application, I noticed that the selected option is not styled correctly when the value of the selected option is `false` or `0`.
https://github.com/alpinejs/alpine/assets/22586858/e3495434-e47d-4858-a6aa-7a09fa79a7cc
This is caused by the `isSelected` getter on `$listboxOption` / `$comboboxOption`. That getter always returns false if the item's value is falsy. That is not correct if the item's value is false or 0. This PR fixes that.

Ensure `$listboxOption.isSelected` / `$comboboxOption.isSelected` works if item value is `false` or `0`

---

packages/ui/src/listbox.js

When I combine Livewire's `wire:navigate` and listbox components, I get the following error when navigating:
The combobox component does not have that issue. When looking at the source code of the combobox, I saw that the `__activateSelectedOrFirst` method is directly accessed on `this` instead of `this.$data`. This PR changes that in the listbox component in the same way, as that fixes the error.

Fix context of listbox to prevent error when using wire:navigate

---

packages/alpinejs/src/lifecycle.js
packages/alpinejs/src/mutation.js
tests/cypress/integration/mutation.spec.js

The goal is to support "add reorder" that happen in the same mutation.
Original PR: https://github.com/alpinejs/alpine/pull/3951 (that was revert because it introduced a bug)

feat: Update lifecycle and mutation

---

tests/cypress/integration/plugins/ui/menu.spec.js

Adds failing test for #4030 
If the `this.$refs.__items` are replaced with `this.$el` in the following section then the test passes, so it seems to be related to teleported refs.
https://github.com/alpinejs/alpine/blob/84fd08d62c1041ed73358a4a0d337656d8d488cd/packages/ui/src/menu.js#L98-L110

Add failing test for keyboard controls with `x-teleport`

---

packages/alpinejs/src/scope.js
tests/cypress/integration/scope.spec.js

Currently, if a class instance is used as the data scope, instance methods (and inherited properties *shudders*) are not accessible in expressions.
This is due to only checking for own properties in `mergeProxies`.
This changes this to use `Reflect.has` to better *reflect* the actual operation being performed, and uses that same behavior in other places doing this check for consistency. (Of note, I found in some testing that using `Reflect.ownKeys` in the `ownKeys` trap caused some very strange call stack issues).
(Note on using Class instances in general: actually private instance properties/methods will not be accessible from other methods on that class instance due to how the proxy reflection actually works).

Allows access to methods when class instance used for x-data

---

packages/focus/src/index.js

fix to allow preventScroll to be set to true when element passed onScroll() method

bug fix __noscroll param

---

packages/persist/src/index.js

Fixed persist crash when the stored value is undefined. This bug crashes Alpine

Fixed persist crash when the stored value is undefined

---

packages/docs/src/en/directives/model.md

Example input for `.fill` is missing a border:
This PR adds the border and makes it look like throttle above.

Add missing border to fill example

---

packages/alpinejs/src/directives/x-model.js
tests/cypress/integration/directives/x-model.spec.js

Fixes #4102 
due to how debounce influenced the handling of the fill event, the model would clear out the input value before the event would be handled.
[demo here](https://awesomealpine.com/play/?coreplugins=0&tw=1&html=PGRpdgogIHgtZGF0YT0ieyB2YWx1ZTogbnVsbCwgb3RoZXI6ICcnIH0iCiAgY2xhc3M9ImZsZXggZmxleC1jb2wgZ2FwLTIgcC04Igo-CiAgPGlucHV0CiAgICB4LW1vZGVsLmZpbGw9InZhbHVlIgogICAgdmFsdWU9ImhlbGxvIgogICAgdHlwZT0idGV4dCIKICAvPgogIDxpbnB1dAogICAgeC1tb2RlbC5kZWJvdW5jZS5maWxsPSJvdGhlciIKICAgIHR5cGU9InRleHQiCiAgICB2YWx1ZT0id29ybGQiCiAgLz4KICA8c3BhbiB4LXRleHQ9ImAke3ZhbHVlfSwgJHtvdGhlcn1gIj48L3NwYW4-CjwvZGl2Pgo&script=Y29uc29sZS5sb2coJ0hpIGN1dGllJyk7Cg)
This instead just directly uses the same methods to update the value. These methods hadn't existed before, which is why the event was used before.
This …

Bug: Fixes x-model.fill when used with debounce

---

packages/alpinejs/src/directives/x-model.js
tests/cypress/integration/directives/x-model.spec.js

This fixes filling model data based on which radio button is checked when the page loads. A very simple example can be found [here](https://codepen.io/willrowe/pen/BaEpRyJ) and this PR also includes a test.
In the Codepen, I expected that `type` in the Alpine data would be set to 'second' after page load and that the 'Second' radio button would be checked. However, `type` is set to 'first' and the 'First' radio button is checked instead.
I did a little bit of debugging and figured out that a `change` event is being triggered when the `.fill` modifier is present. Removing it from the first radio button (second example in the Codepen) makes it work as expected, but it should still work when the modifier is present by filling based on which radio button is currently checked.
The …

Fix fill modifier for radio buttons

---

packages/alpinejs/src/utils/bind.js
tests/cypress/integration/directives/x-bind.spec.js

Fixes: https://github.com/alpinejs/alpine/discussions/4086
This fix will allow you to pass strings to `:hidden` which will allow you to use `hidden="until-found"`. 
More information on [hidden until found](https://developer.chrome.com/docs/css-ui/hidden-until-found).

Remove hidden from booleanAttributes

---

packages/docs/src/en/magics/dispatch.md

In the documentation about dispatch there is a typo. The text says:
> The first example won't work because when **`custom-event`** is dispatched, it'll propagate to its common ancestor, the `div`, not its sibling, the `<span>`. The second example will work because the sibling is listening for `notify` at the `window` level, which the custom event will eventually bubble up to.
But the code snippet doesn't dispatch `custom-event`, it dispatches a `notify` event: `@click="$dispatch('notify')"`

Documentation issue: Event name in code snippet and description doesn't match in dispatch.md

---

packages/alpinejs/src/utils/on.js
tests/cypress/integration/directives/x-on.spec.js

I want to use the `once` and `self` modifiers together, like `@something.self.once`, but the handler never runs if the first event is not from self. I think the reason is that once is evaluated before self. 
This PR fixes the order of evaluating the modifiers so the two work together.
I think the failing test is unrelated.

Fix x-on with both self and once

---

packages/alpinejs/src/mutation.js

`destroyTree` is hooked into `mutation.js` by [lifecycle.js#L22](https://github.com/alpinejs/alpine/blob/main/packages/alpinejs/src/lifecycle.js#L22), and will be called [when an element is removed](https://github.com/alpinejs/alpine/blob/cd171328bffdfc805256d1ada84522898ef5b107/packages/alpinejs/src/mutation.js#L179).
If we [call it again](https://github.com/alpinejs/alpine/blob/cd171328bffdfc805256d1ada84522898ef5b107/packages/alpinejs/src/mutation.js#L181), then we call it twice.
This PR removes the extra call, and it also eliminates the dependency-cycle between `lifecycle.js` and `mutation.js`.

Remove extra destroyTree call

---

packages/alpinejs/src/directives/x-teleport.js
tests/cypress/integration/plugins/morph.spec.js

Morphing the following HTML to itself (like in the case of refreshing a Livewire component) doesn't work and throws an error:
```html
<div>
<template x-teleport="body">
<div>
<template x-for="item in 3" :key="item">
<span x-text="item"></span>
</template>
</div>
</template>
</div>
```
The 3 errors: `Uncaught ReferenceError: item is not defined`
It's worth noting that without the `<template x-teleport="body">` element, this works fine.
Generally speaking, when Alpine morphs, it walks the live tree and the reference tree element by element. Along the way, "cloning" (initializing) the reference tree as it goes and comparing the given elements for differences. If it finds one, it mutates the live DOM and keeps going.
Then, at the end of this process, the Alpine's mutation observer will pick …

Fix morph when x-for is used inside x-teleport

---

packages/alpinejs/src/directives/x-teleport.js
packages/morph/src/morph.js
tests/cypress/integration/plugins/morph.spec.js

The following HTML, when morphed to itself (like in the case of a Livewire component refreshing), will throw an error:
```html
<div>
<template x-teleport="body">
<div x-data="{ foo: false }">
<div x-text="'foo value: ' + foo"></div>
</div>
</template>
</div>
```
The error: `Uncaught ReferenceError: foo is not defined`
Interestingly, the problem does NOT occur when wrapping the `x-data` element in a plain `<div>` like so:
```html
<div>
<template x-teleport="body">
<div>
<div x-data="{ foo: false }">
<div x-text="'foo value: ' + foo"></div>
</div>
</div>
</template>
</div>
```
Clearly during the morph/clone phase, the live tree's `x-data` data is not being brought over to the reference `<div>` during clone.
Alpine's morph algorithm will walk both the live and reference tree, element by …

Fix morphing root level state

---

packages/alpinejs/src/utils/on.js
packages/docs/src/en/directives/on.md
tests/cypress/integration/directives/x-on.spec.js

I have a need to use comma as a separator in autocomplete I am implementing with Alpine. I guess this is an occasional need, as comma is a thousands separator in some countries and decimal separator in others.

Comma modifier to keyup and keydown events

---

packages/docs/src/en/essentials/installation.md

The fact that `x-data` is needed in order to enable any Alpine.js behavior is pretty hidden in the docs. It'd be nice to make it more visible via the getting started guide.

Higher visibility in docs about needing x-data for things to work

---

packages/alpinejs/src/directives/x-transition.js

There is a race condition in Alpine when using `x-transition` and `x-show`. It's tricky to reproduce. The code change here removes the JavaScript error: `Uncaught (in promise) TypeError: i is not a function`.
Normally, `el._x_hidePromise` is a Promise, so calling this is fine. However, when this code runs more than once in quick succession, one copy works just fine, and the next copy passes an `undefined` into the `Promise.all()`, so the `.then()` gets an `undefined`, which it then attempts to call as a function, resulting in the error reported.
The scenario that I've been looking into is a drop-down menu layout where putting my mouse over a top-level element reveals a sub menu. When I move my pointer over these top-level elements slowly, all is well. When I move my pointer over these …

Fix error: TypeError: i is not a function

---

packages/collapse/src/index.js

Sometimes it happens, that the `overflow: hidden` style remains on the element after it has expanded.
The reason is, that there is a condition checking that the element height as reached the full height, but sometimes the values do not match perfectly. For example, `full` is `100.5` but `el.getBoundingClientRect().height` returns `100.4765625`.
This PR changes the condition to allow a difference up to 1px.
To be honest, I am not sure, if the condition is necessary at all.

collapse: remove overflow hidden even if height does not match perfect

---

packages/alpinejs/src/utils/on.js
packages/docs/src/en/directives/on.md
tests/cypress/integration/directives/x-on.spec.js

Handles #4208 
Allows for the use of `ctrl` `meta`...etc keys on click and mouse event listeners.
Overall simple change to include clicks
Would a more significant refactor also enable the use of mouse-button modifiers? Maybe...
This also solved some *potential* bugs related to modifiers that could exist on a keydown that wouldn't be properly ignored.
Includes:

:sparkles: Enhances clicks with key modifiers

---

packages/docs/src/en/directives/transition.md

With a span, the transition effect is not obvious because the element doesn't move so the documentation looks broken.
I confirmed this in MacOS for Firefox, Chrome, and Safari.

Update transition.md - changed span to div

---

packages/csp/src/evaluator.js
packages/docs/src/en/advanced/csp.md
tests/cypress/integration/plugins/csp-compatibility.spec.js

This PR adds a minimal enhancement to the CSP build to support nested properties via dot notation (property accessor).
```html
<div x-data="counter">
<button @click="foo.increment">Increment</button>
<span x-text="foo.count"></span>
</div>
```
```js
Alpine.data('counter', () => ({
foo: {
count: 1,
increment() {
this.count++
},
},
}))
```
The build size is pretty much the same and it seems a reasonable change otherwise dev using the csp build are forced to flatten the component and put all properties at the top.
I only know about one user mentioning it though so feel free to close it if you think it's not worth it for now.

[CSP] Add support for nested properties to CSP build

---

packages/ui/src/tabs.js

Currently a tab gets the focus when you receive the mousedown event instead of the full click.
This is different from how tabs usually work everywhere else (including Tailwind Headless UI that fixed it with this PR: https://github.com/tailwindlabs/headlessui/pull/1192).
Unfortunately, it's not easily testable because cypress doesn't behave that way but chrome and firefox do.
This seem to cause some interoperability issues with x-dialog too: https://github.com/alpinejs/alpine/discussions/4230#discussioncomment-9532452 (The OP didn't provide an example though).

[UI][Tabs] Prevent tab focus on mousedown

---

packages/alpinejs/src/scope.js
tests/cypress/integration/scope.spec.js

Solves an issue presented in Discord
Apparently there is an [upstream bug](https://github.com/vuejs/core/blob/31abdc8adad569d83b476c340e678c4daa901545/packages/reactivity/src/baseHandlers.ts#L148) in @vue/reactivity that, when using a setter to access deeply nested data on a part of `this` that was not in the same object, would error out. As vue was not respecting the `this` context when using reflection.
I intend to make a PR there to address this as well, but Alpine is broken by even updating one minor version, so this still needs to be addressed here.
The issue can be demonstrated here:
[3.13.0](https://awesomealpine.com/play/?coreplugins=0&html=PGRpdgogIHgtZGF0YT0ieyBmb286ICB7IGJhcjogJ2ZpenpidXp6JyB9LCBlcnJvcjogJycgfSIKICBjbGFzcz0icC0yIGZsZXggZmxleC1jb2wgZ2FwLTIgaXRlbXMtY2VudGVyIgogIEB …

:bug: Fixes issue with setters accessing deeply nested data

---

packages/docs/src/en/directives/for.md

While reading the documentation, I noticed a sentence didn't have a closing period. This change adds it.

Minor grammar correction in the for directive docs

---

packages/alpinejs/src/store.js
tests/cypress/integration/plugins/persist.spec.js
tests/cypress/integration/store.spec.js

Solves #4248 
Stores were running their `init` method before interceptors were handled.
This handles interceptors first, just like how `data` does.

:bug: Initializes Interceptors before store

---

packages/docs/src/en/plugins/anchor.md
packages/docs/src/en/plugins/collapse.md
packages/docs/src/en/plugins/focus.md
packages/docs/src/en/plugins/morph.md
packages/docs/src/en/plugins/persist.md
packages/docs/src/en/plugins/resize.md
packages/docs/src/en/plugins/sort.md
packages/resize/builds/cdn.js
packages/resize/builds/module.js
packages/resize/package.json
packages/resize/src/index.js
scripts/build.js
scripts/release.js
tests/cypress/integration/plugins/resize.spec.js
tests/cypress/spec.html

This PR adds a new Alpine plugin called "Resize" with the following API:

Add resize plugin: `x-resize`

---

packages/alpinejs/src/directives/x-for.js
packages/alpinejs/src/directives/x-if.js
packages/alpinejs/src/lifecycle.js
packages/alpinejs/src/mutation.js
tests/cypress/integration/directives/x-for.spec.js
tests/cypress/integration/directives/x-if.spec.js

Eagerly cleans up clones from `x-if` and `x-for` template directives.
Addresses: #4299 #4287 #4231 #1730 #3980 and others...
Basically, when x-if and x-for cleaned up their cloned elements, they mainly left it to the mutation observer to but this was not always correctly handling the tree when it came to these elements. Resulting in primarily non-destructive errors, but also in a significant memory leak.
The x-for would not dequeue any scheduled jobs, so already triggered effects would run even if x-for removed the element, while x-if would dequeue existing jobs, it would actually prevent many cleanups on nested elements from actually being run.
This mainly became an issue when x-if and x-templates were nested (in each other or themselves) as the duplication of elements and effects could …

:bug: Cleans up template directives memory

---

packages/alpinejs/src/utils/bind.js
tests/cypress/integration/directives/x-bind.spec.js

This PR simply updates the list of Boolean Attributes to follow updates in the spec, as well as moves the list out of the function and into a set for improved performance (and sorting my alphabet to make updates easier).
The actual attribute changes are
```diff
- allowpaymentrequest
+ inert
+ shadowrootclonable
+ shadowrootdelegatesfocus
+ shadowrootserializable
```
`allowpaymentrequest` was deprecated a long time ago, so I vote for removal.
Not included is `credentialess` which is a draft attribute, but is supported by everything except FireFox.

:construction: Updates List of boolean attributes to follow spec

---

packages/docs/src/en/plugins/resize.md

Fixed a couple of typos.

---

packages/alpinejs/src/directives/x-teleport.js
tests/cypress/integration/directives/x-teleport.spec.js

As a follow-up to #4300 
When `x-teleport` was nested inside `x-if`, the use of `mutateDom` was preventing x-teleport clones from being cleaned up.
This just applies the same fix to immediately clean up the `x-teleport` clone.
Thanks @mgschoen for finding this regression.

:bug: Cleans teleported clone

---

packages/docs/src/en/directives/bind.md

When I saw this example using `x-data="dropdown()"` and [other examples](https://alpinejs.dev/globals/alpine-data#encapsulating-directives-with-x-bind) using ``x-data="dropdown"`` I wondered what caused this example to require parentheses. It seems like adding parentheses is redundant since the example code works both with and without them.

Remove unnecessary parentheses from bind.md example

---

packages/docs/src/en/directives/bind.md
packages/docs/src/en/directives/for.md
packages/docs/src/en/directives/id.md
packages/docs/src/en/directives/if.md
packages/docs/src/en/directives/model.md
packages/docs/src/en/directives/on.md
packages/docs/src/en/directives/ref.md
packages/docs/src/en/directives/transition.md
packages/docs/src/en/start-here.md

This comes up quite often, that someone is stumped by a directive not working, despite copying it from the docs because it doesn't have an `x-data` parent.
So this adds an extra note in the start here, and a note under the first example that doesn't use `x-data` for each directive (as needed).
It's a sad day.

:memo: Updates docs with notes for x-data usage

---

package-lock.json
packages/alpinejs/src/mutation.js
tests/cypress/integration/mutation.spec.js

Fixes #4449 
Due to the location of the check for "has this element already been initialized", elements that were moved within an alpine component, without a new wrapper element, were being improperly marked as only having been removed, and we summarily cleaned up and not reinitialized.
this just moves that check to just before the element would be reinitialized (Should this check maybe just be part of the lifecycle instead of mutation entirely?)
Includes test for the case that fails if you revert the changes to the mutation code.

:bug: Fixes Regression in Mutation handling

---

packages/alpinejs/src/lifecycle.js
tests/cypress/integration/directives/x-ignore.spec.js

Release v3.14.4 introduce an _x_marker property to flag elements that were already initialised so they don't get initialised again when moved around (I think it was causing some issues in Livewire). However the code was also marking as initialised elements that were skipped by x-ignore.
This causes issues if x-ignore is removed and people calls initTree on the element: the subtree is initialised but the parent is skipped even if it wasn't previously initialised so, if it has x-data, it will trigger errors.
See https://github.com/alpinejs/alpine/discussions/4457
This PR changes the logic so _x_marker is not added when the element has x-ignore

Fix regression on x-ignore when removed

---

packages/alpinejs/src/directives/x-teleport.js
tests/cypress/integration/directives/x-teleport.spec.js

As per the discussion here https://github.com/alpinejs/alpine/discussions/4467#discussioncomment-11461276 I've removed the Teleport clone x-ignore.
I've run the tests locally and they pass. I've also made a build of Livewire with it, run it's tests and all pass.
Fixes #4461, fixes #4467, fixes livewire/livewire#9067

Fix x-teleport by removing clone x-ignore

---

packages/mask/src/index.js
tests/cypress/integration/plugins/mask.spec.js

Currently if you have are using `x-mask` with Livewire and you are using `wire:model.live`, `x-mask` is triggering a network request on page load and changing the default value from `null` to an empty string.
Loading the below Volt component immediately triggers a request and the `dd()` is called.
This PR fixes it by adding a check to see if the `_x_model` value is the same as what is being set by the mask and skips the set. Or if the set value is an empty string and the `_x_model` value is `null` then it will also skip it. This is only for the initial load of the mask. Everything else should still run the same.
Fixes livewire/flux#751
```blade
<?php
use Livewire\Volt\Component;
new class extends Component {
public $phone_number_masked;
public $phone_number;
public function updated()
{ …
```

Fix x-mask triggering update requests on load

---

packages/docs/src/en/plugins/focus.md

Fix the issue in the x-trap.noscroll example code in documentation.

Fix focus documentation example code

---

packages/morph/src/morph.js

This PR adds support to morph for skipping the update of an elements children. This can be used with something like Livewire to add a `wire:ignore.children` directive, to allow an elements attributes to be updated, but for it's children to be ignored.
See Livewire PR livewire/livewire#9229 for more details.

Add skip children to morph

---

packages/focus/src/index.js

Related discussion: https://github.com/alpinejs/alpine/discussions/4634
In recent versions of Chromium, using the `inert` modifier with `x-trap` results in this warning:
> Blocked aria-hidden on an element because its descendant retained focus. The focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.
Here’s a minimal reproduction:
https://codepen.io/magiclantern/pen/vEOjaVg/9827b04ae16fffe57feb1f762870aeaa
This seems to happen because `aria-hidden` is applied by the Focus plugin _before_ focus is trapped in the new container. 
This …

Fix Chrome warning when using `x-trap.inert`

---

packages/persist/package.json

Hi, there. Thank you for the awesome project! I'd like to propose the following change:
- What: add "exports" field to package.json, mapping ESM to ./dist/module.esm.js and CJS to ./dist/module.cjs.js
- Why: tools like Vite default to main when exports is absent, causing CJS to be used in dev server and breaking default export detection.
- How: update package.json, built & tested locally with Vite and Node (import/require).
- Backward compatibility: keeps existing main & module fields.

feat(persist): add 'exports' field for proper ESM/CJS resolution
